### ISSUE TITLE
Faster --test mode

### ISSUE THREAD

**Issue by jmn** [ndmitchell/ghcid#100]
Is it possible to make a faster --test mode? I tried running something like `ghcid -c "stack ghci --test --no-load --ghci-options -fobject-code" -T main` but reload still takes a while. Looking at things like DevelMain.hs from yesod and https://hackage.haskell.org/package/rapid it should be possible to achieve faster reloads.

**Comment by ndmitchell** [comment]
Making things faster would be nice, but I'm not quite sure what technique from rapid you are suggesting?

**Comment by ndmitchell** [comment]
I think rapid is seeing inside the test suite to make it faster, with custom code to initialise separate pieces. If you do that using rapid, then ghcid will benefit, but there's no generic technique in rapid that makes it magically work.
