### ISSUE TITLE
Getting a 'Not an editor command' when calling :Ghcid

### ISSUE THREAD

**Issue by kozross** [ndmitchell/ghcid#113]
I've just set up the plugin using vim-plug, as per the instructions. When I open a Haskell file, and call ``:Ghcid``, I get the following error:

```
E492: Not an editor command: Ghcid
```

I definitely have the right version of Neovim (0.2.2), and ``ghcid`` (0.6.8), and the plugin is definitely installed. Am I missing something?

**Comment by ndmitchell** [comment]
CC  @cloudhead

**Comment by cloudhead** [comment]
Hmm the only thing I can think of is if the file isn't detected as being Haskell - since the plugin only loads for Haskell files. Could that be it?

**Comment by kozross** [comment]
@cloudhead and @ndmitchell: Seems like a re-install fixed this. I am unsure why I got this error, but you can consider this issue resolved. My apologies for the confusion.
