### ISSUE TITLE
Noise in the terminal from Ghcid when running the Neovim plugin

### ISSUE THREAD

**Issue by kozross** [ndmitchell/ghcid#115]
If I open a file with Neovim, and then run ``:Ghcid``, I get some noise in the terminal, as follows:

    [koz@Sebastian graph-colouring]$ e src/Main.hs 

    Ghcid: OK
    Error detected while processing function 7:
    line    2:
    Ghcid: Exited with status 1[koz@Sebastian graph-colouring]$

For reference, ``e`` is an alias for ``nvim``, and the tasks I did were as follows:

1. Open a file with no compile errors
2. Deliberately introduce one
3. Fix it

**Comment by cloudhead** [comment]
This is when you exit vim that you see this? Or on startup?

**Comment by kozross** [comment]
When I exit.

**Comment by cloudhead** [comment]
Can't quite reproduce this. Do you still have this issue? If so, can you provide a minimal example include what's in your `.ghci` file if anything?

**Comment by ndmitchell** [comment]
Can't reproduce and not enough user details so closing. @kozross - please feel free to reopen if you have enough details to reproduce.
