### ISSUE TITLE
Working with ui application?

### ISSUE THREAD

**Issue by coodoo** [ndmitchell/ghcid#119]
I'm poking around [Pong](https://github.com/ekmett/lens/blob/master/examples/Pong.hs) which is a simple desktop game and wondering how does `ghcid` work with this kind of app with an UI, for example, after editing the code, how does one see the updated view?

Currently I have to use `stack run Myapp` every time, which became tedious rather quickly as you could imagine.

**Comment by ndmitchell** [comment]
You can set that as the `--test=:!stack run Myapp`, but then every time you save any file it's doing to spawn your program, which is probably excessive. Might be worth trying though.

When I was last doing GUI's in Haskell I baked it into the GUI framework to auto-restart when saved/compiled, which was mightily handy.

**Comment by ndmitchell** [comment]
Someone wrote a blog post about how to do this: https://binarin.ru/post/auto-reload-threepenny-gui/
