### ISSUE TITLE
ghcid on WSL doesn't get file change notification on drvfs

### ISSUE THREAD

**Issue by TerrorJack** [ndmitchell/ghcid#121]
When launching `ghcid` in WSL for a project located on `/mnt/c/` somewhere, file change notification doesn't work at all. This is confirmed even with `ghcid-0.6.8` and Windows insider build 15063.

WSL claims to have `inotify` support (see [here](https://blogs.msdn.microsoft.com/commandline/2017/04/11/windows-10-creators-update-whats-new-in-bashwsl-windows-console/)) for drvfs. I'm not sure whether this should be a WSL issue, `fsnotify` issue or `ghcid` issue, so I'm opening an issue here for now, feel free to close it if not relevant.

Is it possible to add a polling mode instead of notification? `stack` supports rebuilding on change, and has notification/polling mode. This shall be a viable workaround for this issue.

**Comment by ndmitchell** [comment]
Probably an issue for fsnotify. Ghcid does have a polling mode but it’s not exposed - a command line flag would be easy to add.

**Comment by ndmitchell** [comment]
I added a flag `--poll` which switches back to polling.

**Comment by TerrorJack** [comment]
This now works out of the box on Windows 10 17751, so if anyone else is looking at this issue and want to set up a `ghcid`-based workflow with WSL, try switching to latest insider build (or wait for next Windows 10 release). Still thanks for adding `--poll`!
