### ISSUE TITLE
Add timestamp to "All good" message

### ISSUE THREAD

**Issue by yairchu** [ndmitchell/ghcid#124]
Being used to things not working, when I see the "All good" message I'm never 100% sure that all is really good, or perhaps `ghcid` got stuck. While it never got stuck, this doubt I have and I'm sure many others share would be mostly alleviated if it was timestamped -

    All good (224 modules, at 13:06)

**Comment by ndmitchell** [comment]
Sounds like a great idea. PR most welcome!

**Comment by ndmitchell** [comment]
Done by @vaibhavsagar in #125.
