### ISSUE TITLE
"Auto-update" support

### ISSUE THREAD

**Issue by yairchu** [ndmitchell/ghcid#126]
Not a super important feature, but would be cool if:

Ghcid would also watch the file of its own executable, and when one `stack install`s a new version all running `ghcid`s would restart into the newer version. :)

Note that for any IDE plugins that don't offer an explicit restart of `ghcid` this would help avoid needing to restart the IDE.

**Comment by ndmitchell** [comment]
I have to wonder how common this would be?

Are you assuming the new `ghcid` binary will be written over the old one? On Windows, that doesn't work, since a running executable locks the binary for writing. Does `stack install` write to the same location?

**Comment by yairchu** [comment]
Yes, `stack install` writes to the same location, and I assume if `ghcid` will be included in `apt-get` or equivalent distro packages it will also replace the same location.

**Comment by ndmitchell** [comment]
Currently `ghcid` has three levels of restart - the `--reload` flag (to send a `:reload` to stdout), the `--restart` flag (to kill `ghci.exe` and restart it), and what you describe would require a third one - kill `ghcid.exe` itself and restart. It's never going to work on Windows because Windows doesn't allow overwriting the binary.

**Comment by yairchu** [comment]
Well, I guess when the folks on Windows complain that the auto-update feature doesn't, ghcid could be made to run itself from a temporary location where it copies itself to so that the main binary is over-writable, and until that is implemented auto-update would only work on the other platforms :)

**Comment by ndmitchell** [comment]
That seems overly complex - in fact every aspect of this feature seems relatively complex for something I am not yet convinced will be that widely used...

**Comment by ndmitchell** [comment]
Closing, but if someone comes up with a patch that is very simple I might consider merging it (but personally don't consider it worth the effort to write, and given what I expect the patch to do, nor to maintain).
