### ISSUE TITLE
how to run tests

### ISSUE THREAD

**Issue by mvolkmann** [ndmitchell/ghcid#128]
Sorry to ask what might be a basic question, but what is the command to get tests to rerun when source files are modified?
This command runs the tests once and exits:
`ghcid -c="stack test"`
This command perhaps runs the tests repeatedly, but the only output I see is "All good (2 modules)":
`ghcid -c="stack ghci test/Spec.hs"`

**Comment by ndmitchell** [comment]
See the help output:

```
$ ghcid --help
Auto reloading GHCi daemon v0.6.8

ghcid [OPTIONS] [MODULE]

Common flags:
  -c --command=COMMAND  Command to run (defaults to ghci or cabal repl)
  -T --test=EXPR        Command to run after successful loading
```

You specify a command to get you a `ghci` prompt, and a command to run in that `ghci` prompt which runs the tests. One way to go is `ghcid -c="stack ghci test/Spec.hs" -T=main`. An alternative would be `-T=":!stack test"`.

**Comment by mvolkmann** [comment]
Excellent! Thanks Neil!
