### ISSUE TITLE
Failed when hiding source paths

### ISSUE THREAD

**Issue by hrls** [ndmitchell/ghcid#132]
ghcid failed when GHC option _-fhide-source-paths_ enabled in stack.yaml.  
![screen shot 2018-01-31 at 18 42 13](https://user-images.githubusercontent.com/3259009/35632019-866ab378-06b6-11e8-88e9-44b558e2ccd7.png)

**Comment by ndmitchell** [comment]
I figured it out in the end, so all supported now.
