### ISSUE TITLE
Making ghcid more usable by external tools

### ISSUE THREAD

**Issue by merijn** [ndmitchell/ghcid#134]
So, ghcid seems to be the only interactive tool that actually works reasonably with `new-build` I'm trying to get it working with vim and neomake (I don't have neovim available, so sadly the existing nvim plugin doesn't quite work). I'd like to propose some minor tweaks that make ghcid slightly more friendly to tooling. I'm already implementing this stuff, so this issue is more to discuss behaviour preferences to get the finished work merged back into ghcid (because I don't wanna keep porting it forward indefinitely).

Desirable changes when reading ghcid output in tools:
* Disable ANSI colouring
* Don't linewrap
* Sentinel output to indicate the end of error/warning list

My personal changes to the design would be as follows (but I'm open to ensuring the default behaviour doesn't change and putting all the above changes behind flags, if you prefer to preserve the current behaviour at all cost):

* Auto-detect when ghcid is talking to an ANSI terminal.
* Disable ANSI colouring when not talking to a terminal (unless a new flag forces colouring on).
* Disable the linewrapping/error truncation when not talking to a terminal (unless an explicit width/height are passed in on the command line).
* Output a sentinel at the end of output when height is not limited. (This is the change I'm most torn about, it might be nicer to just never output a sentinel unless explicitly instructed by a flag...)

While this changes some of the default behaviour of ghcid, it shouldn't affect most usecases, as I think in most cases people use it attached to a terminal anyway. But, as I said, I'm open to preserving the current behaviour as-is and hiding all my changes between flags if that's preferred.

**Comment by merijn** [comment]
After playing around a bit with it, I think a lot of the terminal code is rather deeply intertwined with the other ghcid code so that making these changes becomes rather invasive.

A hacky, but much simpler approach might be to not change any of default behaviours at all and just add the ability to inhibit doing output at all. Because then the desired effect can be achieved by simply running `ghcid` with `-o /dev/stdout`, which already logs all messages without any wrapping  or ANSI colour noise.

**Comment by merijn** [comment]
That would still necessitate adding a flag to output some sentinel line to distinguish when error reports end, but that should be fairly easy. Which would reduce any changes to one flag to write such a sentinel line and another flag to inhibit the standard output, which should also be fairly trivial.

**Comment by ndmitchell** [comment]
Happy to make changes. I guess the first question is how you interact with it - I expected that for downstream tooling the `-o` output mode would be easiest - that's what the VS Code plugin uses. With respect to that:

* It doesn't do line breaking, so no issues there - basically it assumes an infinitely sized canvas.
* It doesn't add coloring, so again, all good there.
* It writes the file atomically - specifically to another location and then renames at the end. That way you can just watch the file, and you get atomicity in the consumer without a sentinel.

How does that change what you still require?

**Comment by merijn** [comment]
@ndmitchell Ok, after diving into the source more, the more I realise making the ghcid executable support what I want seems kinda pointless, as it involves optionally disabling like 90% of the code. Currently I'm just using the ghcid inspiration to write the tool I need using the ghcid library.

The only change I'd like to see is that, currently, `startGhci` uses `shell` from the process library to start ghci, which rather breaks things on my system, as `ghci` is actually aliased to a specific `.ghci` files, etc.. So I would like to propose a change that uses `proc` to run `ghci`, ensuring it runs the actual executable, not any shell aliases/scripts.

Since that'd be a breaking change that changes a lot about how `startGhci` works, I understand if you wanna keep it as-is, but at the very least I'd like to add an alternative/variation (not quite sure how it should be named) of `startGhci` that uses `proc`. I can make a PR for that if it's ok with you (and feel free to chime in with any naming suggestions).

**Comment by ndmitchell** [comment]
The fact it uses `shell` is not an accident - many companies have custom `ghci.bat` or `ghci.sh` files that set up their environment to work with `ghci`, so it is critical. How about adding:

```haskell
startGhciProcess :: CreateProcess -> (Stream -> String -> IO ()) -> IO (Ghci, [Load])
```

Then you can specify exactly what you want and the existing `startGhci` can just forward on to that new function?

**Comment by merijn** [comment]
I was thinking of something like `startGhciProc :: String -> [String] -> (Stream -> String -> IO ()) -> IO (Ghci, [Load])` as alternative variation of `startGhci` and then forwarding them both to your suggestion. Or, alternatively just have all 3 variations to cover all bases.

**Comment by ndmitchell** [comment]
I suggest `startGhciProc` should take a `FilePath` for the current directory, for symmetry with `startGhci`, which should really have been called `startGhciShell` (but probably too late now?).

**Comment by merijn** [comment]
I renamed `startGhci` to `startGhciShell` (keeping a deprecated `startGhci` alias) and added `startGhciProc`. I didn't expose the underlying `CreateProcess -> (Stream -> String -> IO ()) -> IO (Ghci, [Load])` since some of the `CreateProcess` fields get overridden, so that seems inelegant, although I'm ok with exposing that function too.

Personally I'm ok with nuking the `startGhci`, but I'm generally more gung-ho about backwards compat breaking changes, so I kept it around for now. (See #142)

**Comment by merijn** [comment]
@ndmitchell Ping?

**Comment by ndmitchell** [comment]
Delayed pong! Merged now!

Is there anything else to be done in this issue or are all the problems now solved?

**Comment by merijn** [comment]
Works for me, cheers.
