### ISSUE TITLE
Neovim plugin's terminal window jarringly changes size when window layout changes

### ISSUE THREAD

**Issue by bradlarsen** [ndmitchell/ghcid#135]
Using the neovim plugin, when the `:Ghcid` output window is open, and neovim's window layout changes, such as when opening or closing the quickfix window, the `:Ghcid` output window jarringly changes height.

**To reproduce:**
1. In Neovim, with the ghcid plugin enabled, open a suitable Haskell file
2. Turn on ghcid with `:Ghcid` and wait for it to load successfully
3. Introduce a type error or a warning in the Haskell code that gets ghcid to complain
4. Observe that the `:Ghcid` output window opens with ghcid's output
5. Change neovim's window layout by opening the quickfix window (`:copen`)

**What you should see:**  the `:Ghcid` output window increases in height to approximately 1/2 the terminal height.

**What is desired:** the `:Ghcid` output window doesn't change in height

**Comment by ndmitchell** [comment]
Closed in #136
