### ISSUE TITLE
Hacking GHC with ghcid

### ISSUE THREAD

**Issue by aspiwack** [ndmitchell/ghcid#140]
I've been using ghcid for projects where the usual tools (intero, dante, …) don't work for me. Ghcid has proved to be super reliable compared to everything else, if less potent.

Now, it occurred to me that the biggest such project I was working on is GHC. It breaks pretty much all assumptions of Haskell projects: not even having a cabal file. I spent a lot of time rebuilding GHC hunting for type errors.

So here is the big question: does someone know how to write an invocation of ghcid which will track ghc's files?

**Comment by ndmitchell** [comment]
`ghcid` knows nothing about `cabal` etc, only `ghci`. So a better question is can you write a `.ghci` file that brings all of GHC's modules into scope in `ghci`? Once you've got that nailed, the rest is easy.

**Comment by aspiwack** [comment]
Indeed! But, and I may be mistaken here, I'm under the impression that the only reason that anybody would have to write such a `.ghci` file is to be used conjointly with ghcid. Hence my opening a ticket here.

There is documentation for using ghci with GHC out there, but it seems to be only with the purpose of opening one particular module (and `:t` in it).

**Comment by ndmitchell** [comment]
I've got it working in `ghci` and `ghcid`. My instructions are designed for someone building using Hadrian with Stack. I did all the testing on Windows, but I don't think there's anything Windows fundamental.

First grab the .ghci file from [here](https://gist.github.com/ndmitchell/eb5e42443065c0e3a90dbf97199fe758) and put it in `compiler/.ghci`.

 For `ghci`:

```
cd compiler
stack exec --stack-yaml=../hadrian/stack.yaml -- ghci -package-db=../_build/stage0/bootstrapping.conf
```

For `ghcid`:

```
cd compiler
stack exec --stack-yaml=../hadrian/stack.yaml -- ghcid -c "ghci -package-db=../_build/stage0/bootstrapping.conf"
```

* I suggest someone tries upstreaming the `.ghci` file - volunteers welcome!
* Before it starts loading any files it first runs CPP on everything that needs it. That's a huge number. Using a lot less CPP would drastically improve the compile times in ghci.
* On every change it reruns the preprocessor on _every_ file, which causes a massive slowdown. If it only ran the preprocessor on the files that changed it would be amazingly faster. This is worthwhile for other preprocessors in `ghci`.
* `:set -package-db=X` doesn't seem to have any effect in `ghci`. Would slightly simplify the instructions above.

**Comment by aspiwack** [comment]
That's stupendous!

@ndmitchell, I'm having troubles with Hadrian to reproduce your steps (in that I can't seem to build GHC with Hadrian). Could you give me a commit reference on GHC so that I could try them out?

**Comment by ndmitchell** [comment]
@aspiwack - I suggest you reach out to the Hadrian project at https://github.com/snowleopard/hadrian and raise a ticket for them. They'd be more than happy to help you build GHC with Hadrian, and hopefully in the process fix some of their bugs as well.

**Comment by ndmitchell** [comment]
See also https://twitter.com/ezyang/status/978479243360382976

**Comment by ndmitchell** [comment]
See https://github.com/snowleopard/hadrian/issues/551 which is in progress

**Comment by aspiwack** [comment]
Indeed. Basically this wikipage: https://ghc.haskell.org/trac/ghc/wiki/Building/InGhci answers the question to my satisfaction. It may be improved on later by wider hadrian adoption. But in the mean time, let me close this issue and thanks for your effort!

**Comment by ndmitchell** [comment]
Leaving open, as I'd really like to get a `.ghcid` file into the GHC repo that does the right `ghcid` magic...

**Comment by aspiwack** [comment]
I'll be the first to admit that it would be great!

**Comment by mgsloan** [comment]
Here is a `.ghcid` file that works pretty darn well :+1:

```
--command utils/ghc-in-ghci/run.sh
--reload compiler
--reload ghc
--reload includes
--restart utils/ghc-in-ghci/run.sh
--restart utils/ghc-in-ghci/load-main.ghci
--restart utils/ghc-in-ghci/settings
```

I've included it as part of https://phabricator.haskell.org/D4904, which depends on https://phabricator.haskell.org/D4986 .  I've pushed a branch based on recent master, which has a single commit that includes both changes: https://github.com/mgsloan/ghc/tree/ghci-inception

It requires that  and  be merged.  I've put up a branch here that has both files and also adds the .ghcid https://github.com/mgsloan/ghc/tree/ghci-inception

**Comment by aspiwack** [comment]
@mgsloan thanks! I'm looking forward to seeing it merged!

(@kcsongor's script has proved quite useful to me already)

**Comment by mgsloan** [comment]
@aspiwack Cool!  Yeah I was quite stoked to see the .ghci script, very handy.  Without it, you have to be an extremely patient programmer to hack on GHC.

One difference to note with my branch is that it loads `Main` and enables `GHCi`.  This means that you can run ghc from within ghci.  In particular, if you run `main`, then it will start up a nested ghci where you can try out any new modified behaviors

**Comment by kcsongor** [comment]
@mgsloan This is nice! The way I work around this is by, in addition to loading GHC, I additionally load a simple module that uses the GHC API to compile files, and then run that instead, essentially resulting in something similar to your ‘main’ workflow

**Comment by mgsloan** [comment]
I see!  Thanks a bunch for putting together the .ghci script, it really made working on GHC *far* more enjoyable.  I really like being able to use the nested ghci, because you can directly play around with whatever behavior you're changing.  Much quicker than, say, writing a bunch of testcases (though those are good to!).

I have some rough plans to put together something that allows for a single `ghci` to pretend to be multiple processes.  So, it would put a dir on the PATH that contains an executable called `ghc` that really just establishes a connection to your `ghci`, and asks it to run `main` with a particular set of arguments.  So, my eventual goal is to be able to run the testsuite, unmodified, against your GHC-loaded-into-GHCi instead.

**Comment by ndmitchell** [comment]
Given the existence of https://github.com/ghc/ghc/blob/master/.ghcid I'm going to call this well and truly solved. Nice work everyone!

**Comment by mgsloan** [comment]
:+1: And https://phabricator.haskell.org/D5015 got merged, so now you can really just run `ghcid` and away you go!  (need to have stage 2 build first).  I have updated https://ghc.haskell.org/trac/ghc/wiki/Building/InGhci
