### ISSUE TITLE
Programmatically access ghcid's status

### ISSUE THREAD

**Issue by srid** [ndmitchell/ghcid#143]
My use case: I want to create something that does `:r` followed by `main` in GHCi whenever ghcid succeeds in rebuilding the project (`main` here runs a web server, so this effectively reloads the web server). 

It is not totally clear to me how to do this, specifically having ghcid inform another process that it has succeessfully rebulit the project. Is there a way to do this?

**Comment by srid** [comment]
Just discovered the `-T` flag!

**Comment by ndmitchell** [comment]
Awesome, was just about to ask if `-T` met your needs :)

**Comment by srid** [comment]
I still need to figure out a way to talk to a ghci session from outside ...

**Comment by ndmitchell** [comment]
https://hackage.haskell.org/package/ghcid-0.6.10/docs/Language-Haskell-Ghcid.html has ways to access ghci from outside - it's what ghcid is built on. It won't solve all use cases though.

**Comment by srid** [comment]
@ndmitchell So I realized that I don't need to have a separate ghci session, and that I can instead re-use that of ghcid. This way I can run Reflex frontend apps using jsaddle-warp straight from ghcid's ghci session, and thereby get automatic server reloading for free! 

cf. commit above.
