### ISSUE TITLE
"-fdiagnostics-color=always" not being enabled by default

### ISSUE THREAD

**Issue by vaibhavsagar** [ndmitchell/ghcid#149]
This might be premature, but I saw 39a95483b3133d22d89a68d19a41bda9fb3a79ae and wanted to try it. I'm running `HEAD` but not seeing coloured output unless I enable it myself (with e.g. `ghcid --command="ghci Main.hs -fdiagnostics-color=always"`). I tried this with both GHC 8.2.2 and GHC 8.4.1 on Linux. Is there something obvious I'm missing?

**Comment by vaibhavsagar** [comment]
In case it's relevant, here's the `shell.nix` file I used for GHC + `ghcid`:

```nix
let
  fetch   = (import <nixpkgs> {}).fetchFromGitHub;
  nixpkgs = import <nixpkgs> {};
  overrides = self: super: {
    ghcid' = nixpkgs.haskell.lib.overrideSrc super.ghcid {
      src = fetch {
        owner  = "ndmitchell";
        repo   = "ghcid";
        rev    = "9773482fd83bf0bc528bbcb0ad121191a8fd809b";
        sha256 = "18wi0ghxl9kszivyf50aixpbq7srrdncawk7x1fzxhyimm89qqqq";
      };
      version = "0.6.11";
    };
  };
in nixpkgs.mkShell {
  buildInputs = [ ((nixpkgs.haskell.packages.ghc841.override {overrides = overrides;}).ghcWithPackages (p: [ p.ghcid' ])) ];
}
```

**Comment by vaibhavsagar** [comment]
I tried this with Stack as well to rule out Nix weirdness and the command used doesn't include `-fdiagnostics-color=always`:

```
$ git clone https://github.com/ndmitchell/ghcid
$ cd ghcid
$ stack init
<...>
Downloaded lts-11.4 build plan. 
<...>
$ stack build
<...>
$ stack exec -- ghcid
<...>
No files loaded, GHCi is not working properly.
Command: stack ghci --test --no-load --ghci-options=-fno-code --ghci-options=-fno-break-on-exception --ghci-options=-fno-break-on-error --ghci-options=-v1 --ghci-options=-ferror-spans
```

I also tried the Stack-built `ghcid` with my other project and got the same uncoloured output as before.

**Comment by vaibhavsagar** [comment]
This patch results in the behaviour I expect, but I'm assuming it isn't like this for older GHC compatibility reasons?

```patch
diff --git a/src/Ghcid.hs b/src/Ghcid.hs
index 7c08a83..7d39a3c 100644
--- a/src/Ghcid.hs
+++ b/src/Ghcid.hs
@@ -125,7 +125,7 @@ autoOptions o@Options{..}
         let cabal = filter ((==) ".cabal" . takeExtension) files
         let opts = ["-fno-code" | null test] ++
                    -- flags that are set by :set, but are useful earlier, and are GHC-version agnostic
-                   ["-fno-break-on-exception","-fno-break-on-error","-v1","-ferror-spans"]
+                   ["-fno-break-on-exception","-fno-break-on-error","-v1","-ferror-spans","-fdiagnostics-color=always"]
         return $ case () of
             _ | stack ->
                 let flags = if null arguments then
```

**Comment by ndmitchell** [comment]
Yep, I don't want that for older GHC compatibility reasons.

However, `ghcid` does a `:set -fdianostics-color=always` immediately after loading, so while it won't color any errors/warnings from startup, it should start doing the colors on any subsequent errors. To test, just resave/touch one of the files that is listed as having non-colored warnings/errors. Do they then change to having color?

**Comment by vaibhavsagar** [comment]
Ah, this is exactly what I was missing! I can confirm it works after modifying the file in question. Thanks!

**Comment by ndmitchell** [comment]
I added a note at the bottom of the README.
