### ISSUE TITLE
feature request: sort output by module name

### ISSUE THREAD

**Issue by lspitzner** [ndmitchell/ghcid#153]
when using `ghci -j` you can get errors for multiple modules at the same time. For some reason it appears that the order of the errors can depend on the timestamps of the relevant module files. This has the unfortunate side-effect that after editing and saving the file with the first error the first error now is in a different module. If the first edit was just to insert some typed hole then switching to the next module is _not_ what you want. (especially in some larger-scale refactoring with 20+ erroring modules..)

One workaround is to `touch` all modules in your source dir, which seems to "reset" the ordering.

I am not sure who exactly is "at fault". I may have observed this with just ghci but it is rather elusive behaviour when you try to reproduce it.

But as ghcid gathers the messages anyway, perhaps the easiest fix is the title. I'd be willing to code that up, presuming it makes sense. Thoughts?

**Comment by lspitzner** [comment]
> Is using -j a good idea with ghci? What goes worse? Should ghcid enable it unconditionally?

It seems to help - a bit. Just tested the reload speeds on a 25kloc project by applying some non-breaking change to its local "Prelude". Without `-j` 31sec; with `-j` 21sec (avg, N=3). Of course this depends on how deep your module tree is, and how many cores you have.

Not aware of anything else that is worse.

> Were you thinking of sorting by file name? Or a more refined solution?

Haven't considered; anything stable is fine by me, really.

**Comment by ndmitchell** [comment]
Hmm, in fact the modtime does matter a lot - you want the _latest_ file you edited to show up at the top. How about if there are multiple errors you pick the one which was edited latest?

**Comment by lspitzner** [comment]
When refactoring I usually fix stuff in the order the errors are presented in. So if that was not dependent on modtime, the first edit would be for the topmost module anyway.

You make a good point though; there are very good use-cases for what you describe: If you do some "refactoring exploration" where you change some type of some widely used stuff, and test if this change makes sense by looking at some specific code that revolves around that type, even if there are 10 other modules affected (some of which might easily come earlier by some ordering), the "modtime affects order" may be useful.

But I have not consciously encountered that use-case as a pain-point yet, so I'd be inclined to make it a separate feature request.

Also I think we don't need to decide which is the best behaviour, as we can (and probably should) hide any reordering logic behind some `ghcid` flag. Let practice decide which behaviour is more useful.

**Comment by ndmitchell** [comment]
I dislike flags where they provide little benefit. A flag like this would almost never be discovered or set by anyone - it's just not important enough. I think it needs a really good default.

In your refactoring example you want to fix in the order they are presented. If you fix the first one, and its still an error, it will remain at the top. If you want to fix another module, but get it wrong, it is the one you care about. I think both use cases can be fixed with the same approach.

**Comment by lspitzner** [comment]
Right. I just find it hard to anticipate on the dry which will be the best default, or how exactly either approach will behave in practice.

If you `git stash save` your refactoring, you essentially reset all modtimes to the same value.

**Comment by lspitzner** [comment]
Of course both approaches are better than the current behaviour, so I am fine with blessing either as the default and keeping the option open to change should something annoying about it should turn up.

**Comment by ndmitchell** [comment]
Yep, always have the option to change, if it turns out not to work in practice. I'll push the modtime idea and see where we get to.

**Comment by lspitzner** [comment]
Great, thanks!

**Comment by ndmitchell** [comment]
I now set `-j` and sort by modtime on errors, which seems to give a pretty good solution. Please reopen if you feel it needs tweaks.
