### ISSUE TITLE
aborting ghcid while loading does not exit child process

### ISSUE THREAD

**Issue by lspitzner** [ndmitchell/ghcid#154]
to reproduce, take any sufficiently large project, and

1) run ghcid
2) ctrl-c before it finished loading for the first time, when it pauses at the "GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help" line

I see zombie process(es) afterwards. In this case, with using `-c cabal new-repl`, i see three processes: 1) cabal new-repl 2) cabal act-as-setup and most annoyingly 3) a ghc process that keeps one core busy and keeps eating more and more memory at a rate of 1GB per minute or something. Almost got my system oom'd twice just now.

**Comment by ndmitchell** [comment]
Thanks- I think I've identified the issue and have a fix in place.

**Comment by ndmitchell** [comment]
I believe this is now fixed in HEAD - certainly on Windows it works in all the cases I've tried.

**Comment by simonmichael** [comment]
I feel as if this is still happening to me on mac, quite often, though ghcid --version said 0.7 which should have this fix. I often kill ghcid with ctrl-C. I typically start with
```
ghcid -c 'stack exec -- ghci  -rtsopts -Wall -fno-warn-unused-do-bind -fno-warn-name-shadowing -fno-warn-missing-signatures -fno-warn-orphans -fno-warn-type-defaults  -ihledger-lib -ihledger-lib/other/ledger-parse -ihledger -ihledger-ui -ihledger-web -ihledger-web/app -ihledger-api     -DPATCHLEVEL=233 -DDEVELOPMENT -DVERSION="\"1.10.99\"" hledger/Hledger/Cli/Main.hs'
```
using stack version 1.8.0, Git revision 8ba673f3657c9230e5ada6cee198a7a4842e3775 x86_64 hpack-0.28.2. I'm not sure what version of Cabal it's built with. There was a report on #haskell today of the problem still occurring with cabal-[new-]repl, also. I've upgraded to ghcid 0.7.1 and will watch it more carefully.
