### ISSUE TITLE
Allow disabling colours in GHC errors.

### ISSUE THREAD

**Issue by merijn** [ndmitchell/ghcid#155]
Right now `startGhciProcess` and `startGhci` specify `:set -fdiagnostics-color=always`, which is rather awkward for machine processing as all errors get cluttered with shell colour escape sequences. Could this be made optional?

**Comment by ndmitchell** [comment]
In the last released version of Ghcid it always did `-fdiagnostics-color=never`. In the version yesterday morning it always did `-fdiagnostics-color=always`. In the version as of yesterday night it doesn't do either in the API - which means it will usually not have color - essentially following your request. Can you confirm it's as you want it now?

**Comment by merijn** [comment]
My bad, looks like I cloned at an unfortunate time so I could use `startGhciProcess` :)
