### ISSUE TITLE
Run HLint on each file

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/ghcid#158]
For each file, it should run HLint on the file if it can and integrate the output.

**Comment by ndmitchell** [comment]
Maybe this would work better if HLint was a persistent process?

**Comment by ndmitchell** [comment]
Step 1: Do it using what we have now, doing a single run of HLint on all files that have changed.
Step 2: See if it's slow.

**Comment by I3ck** [comment]
I just wanted to create an issue for this.  
I'd love to see the HLint output once there's no more issues.  
  
All good (N modules, at TIME)  
Following improvements are suggested:  
  
Could be added as an option.

**Comment by LeventErkok** [comment]
+1 from me; HLint integration would be really nice.

**Comment by mrkkrp** [comment]
Is this hard to do in general or you just don't have enough time to add this? Or is it of low priority? If someone wanted to pick this up, how hard in your opinion this could be?

**Comment by ndmitchell** [comment]
@mrkkrp I suspect it's not hard, I think it would be useful, but I haven't had any time to look at it. i'd welcome contributions!
