### ISSUE TITLE
Move "Variable not in scope:" errors to the top

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/ghcid#159]
Often GHC will have a not in scope error, followed by a type error because i guessed about the variable. The not in scope errors should be presented first in the list.

**Comment by Wizek** [comment]
This is a +100 from me! I've been baffled by this so many times! Perhaps it would be worth it to fix this in GHC too?

**Comment by Wizek** [comment]
I might be up for some of that if we clarify first whether this is a GHC issue. Would you happen to have an example file on which this issue is reproducible in ghcid, so I could try the same on ghc? I'm not immediately certain how I could construct one such synthetic repro case, so I am hopeful you might have one.

**Comment by Wizek** [comment]
Yeah, same here. Let's see which one of us runs into this again first. :)

**Comment by Wizek** [comment]
Came up with a repro case:

```
module Main where

foo :: String
foo = show a
  where a = baz

bar :: Int
bar = 1

main = putStrLn foo
```

ghcid says this:

**Comment by Wizek** [comment]
Ah, nevermind, that was ghc-7.10, seems to be broken with ghc-8.4.3, so a regression.

**Comment by Wizek** [comment]
Tried a few more versions with Nix, the regression seems to have been introduced in ghc-8.0.x.

**Comment by ndmitchell** [comment]
Good work! Please link to the GHC ticket once you create one.

**Comment by Wizek** [comment]
Done: https://ghc.haskell.org/trac/ghc/ticket/15539

**Comment by ndmitchell** [comment]
Fixed upstream, so nothing for ghcid to do!
