### ISSUE TITLE
Alternate configuration file

### ISSUE THREAD

**Issue by aztecrex** [ndmitchell/ghcid#160]
In our workflows, using the repl and using ghcid have very different configuration requirements. We would like to use a ghcid-specific configuration that ignores the normal ghci configuration hierarchy.

If this is possible now, I can't find any documentation for it. If it's not possible now, I suggest it as a feature and hope for feedback.

**Comment by ndmitchell** [comment]
Have you seen `.ghcid` files? Basically create a `.ghcid` somewhere in this directory or a parent, and that will be the command `ghcid` runs. e.g. `-c "ghci -extra-flag -more-settings"`.

**Comment by ndmitchell** [comment]
Leaving this ticket to document the `.ghcid` information.

**Comment by ndmitchell** [comment]
Now documented.
