### ISSUE TITLE
ghcid is slow to :reload

### ISSUE THREAD

**Issue by mitchellwrosen** [ndmitchell/ghcid#161]
Hi Neil, for some reason `ghcid` is slow to reload on one of my laptops. Here is what I see for about a second after touching a file, when running with `-v`:

```
%WAITING: /home/mitchell/haskell/generic-websockets-server/.ghcid generic-websockets-server.cabal cabal.project /home/mitchell/haskell/generic-websockets-server/Main.hs
%WAITING: /home/mitchell/haskell/generic-websockets-server
%NOTIFY: Added "/home/mitchell/haskell/generic-websockets-server/4913" 2018-05-10 23:54:33.586551059 UTC
%NOTIFY: Modified "/home/mitchell/haskell/generic-websockets-server/4913" 2018-05-10 23:54:33.586556259 UTC
%NOTIFY: Removed "/home/mitchell/haskell/generic-websockets-server/4913" 2018-05-10 23:54:33.586557934 UTC
%WAITING: Notify signaled
%WAITING: Extra wait due to file removal
%NOTIFY: Added "/home/mitchell/haskell/generic-websockets-server/Main.hs~" 2018-05-10 23:54:33.58715762 UTC
%NOTIFY: Removed "/home/mitchell/haskell/generic-websockets-server/Main.hs" 2018-05-10 23:54:33.587152404 UTC
%NOTIFY: Added "/home/mitchell/haskell/generic-websockets-server/Main.hs" 2018-05-10 23:54:33.588629137 UTC
%NOTIFY: Modified "/home/mitchell/haskell/generic-websockets-server/Main.hs" 2018-05-10 23:54:33.590324537 UTC
%NOTIFY: Removed "/home/mitchell/haskell/generic-websockets-server/Main.hs~" 2018-05-10 23:54:33.590705737 UTC
```

Do these two lines indicate that `ghcid` is waiting for an extra second intentionally?

```
%WAITING: Notify signaled
%WAITING: Extra wait due to file removal
```

Thanks!

**Comment by ndmitchell** [comment]
Yep, the extra wait is deliberate to work around the pattern where a text editor writes to A by first deleting it then writing it afresh. Are you using the same editor/OS on the laptop? What is the file 4913 doing - does that have any relevance to you? It may be a temp file I should ignore when it notifies.

**Comment by mitchellwrosen** [comment]
Cool, I'm happy to implement this if you'd like!

**Comment by ndmitchell** [comment]
Reading the messages more carefully, your `ghcid` is being woken up by the 4913 file, but in all likelihood that's happening roughly the same time as an edit, so isn't going to be a problem (if it does turn out to be the issue, we can filter it out). However, the 1s extra wait is only triggered for files it really was watching. I've just pushed fafdc5858eac24dae7498139e872ccd9495fcedf giving a better log message in that situation, saying which file had disappeared. Can you try that?

**Comment by mitchellwrosen** [comment]
Ah! Thanks for that. `nvim` is actually deleting the haskell file itself before writing it back:

```
%NOTIFY: Removed "/home/mitchell/haskell/generic-websockets-server/Main.hs" 2018-05-10 23:54:33.587152404 UTC
%NOTIFY: Modified "/home/mitchell/haskell/generic-websockets-server/Main.hs" 2018-05-10 23:54:33.590324537 UTC
```

**Comment by ndmitchell** [comment]
Yep, that's what it indicates - are you perhaps using an older `nvim` on the troublesome machine? Or some configuration that causes it to do the delete first? If there's no way to avoid it with `nvim`, then I could change from sleep 1s, to sleep in 0.1s increments waiting for the file to come back, which should make the latency way better.

**Comment by mitchellwrosen** [comment]
There should be a way to configure `nvim` to behave differently, I just haven't figured it out yet. It's a bit of a puzzler since my `.vimrc` file is fairly bare-bones on all of my machines, and I've never had to explicitly opt out of this behavior in the past.

I'll track it down eventually, but in the meantime - perhaps `ghcid` could, instead of sleeping upon noticing a relevant file was removed, also act on that deleted file coming back? In my case, this would fix the latency issue, as `Main.hs` is written immediately after being removed.

**Comment by ndmitchell** [comment]
Ghcid can do that, and it does. But you'll really upset ghci which is super buggy if files are deleted and then return...

**Comment by ndmitchell** [comment]
Instead of waiting 1s, I wait up to 1s, but check every 0.05s if the file has returned, and if so stop waiting then. Hopefully that means in the common case you are only sleeping 0.05s which should be mostly imperceptible.

**Comment by mitchellwrosen** [comment]
Much appreciated
