### ISSUE TITLE
Conflict with `:set +t` ghci option

### ISSUE THREAD

**Issue by paraseba** [ndmitchell/ghcid#162]
One of the lines in my global .ghcid configuration file is

```
:set +t
```

With this line, ghci displays type information after evaluation:

```
Prelude> 1
1
it :: Num p => p
```

Version 0.7 of ghcid seems to have an issue with that `it` output line, which makes it continuously reload the code. 

Adding `--verbose` I get this relevant error message:

```
Reloading...
  Error when waiting, if this happens repeatedly, raise a ghcid bug.
  /home/.../it :: ()/: can't watch what isn't there!: does not exist
```

This error wasn't happening with the previous version, I have had `:set +t` for a long time with no issues.

**Comment by ndmitchell** [comment]
Thanks for the report! I rewrote the parsing, and I'm guessing before this got treated as an ignored line, and now it manages to accidentally be treated as a file, with bad consequences. I'll sort it out and make a release tonight, with luck.

**Comment by ndmitchell** [comment]
I think it's actually because I now ask for `:show paths` and that gets confused with the `it :: ()` that comes from a previous line. Easiest thing to do is always disable `+t` inside, which I've now done.

**Comment by paraseba** [comment]
This is great, thanks so much!
