### ISSUE TITLE
error output parsing

### ISSUE THREAD

**Issue by lspitzner** [ndmitchell/ghcid#170]
This is mostly a documentation feature request.

In order to get jump-to-error functionality in my editor, I use `ghcid -o` and have the editor take and parse that as the "build output". In recent versions (of ghcid or perhaps ghc?) the line-numbering format got more complex, for example there now can be

~~~~
Foo.hs:13:1-3:errortext
Foo.hs:(13,1)-(14,2):errortext
~~~~

This requires a mildly complex regex to break it down to a jump-to'able location; e.g. I use the following (perl) regex:

~~~~
^(\\S*?):(?|(\\d+):(\\d+)(?:-\\d+)?|\\((\\d+),(\\d+)\\)-\\(\\d+,\\d+\\)):([^\n]*)
~~~~

which captures: filename, line, column, error string.

Perhaps others may find this regex useful. Alternatively a new flag that formats things in a way easier to parse might be helpful.

**Comment by ndmitchell** [comment]
It's a consequence of `-ferror-spans` which I recently enabled in `ghcid`. The strings are coming directly from GHC, so don't want to modify them. Added as an FAQ at https://github.com/ndmitchell/ghcid/commit/533bb34540ccb311219d99ce41f6be0843e5d8e8 - thanks for sharing the regex!
