### ISSUE TITLE
Question: does ghcid loads modules in parallel or one by one?

### ISSUE THREAD

**Issue by ChShersh** [ndmitchell/ghcid#177]
I wonder whether `ghcid` loads all Haskell modules (when given `cabal new-repl` or `stack repl` command) in parallel or one by one? Is it guaranteed that next module will be loaded only after previous one is processed.

**Comment by ndmitchell** [comment]
This depends on the underlying `ghci` process. Concretely, unless you pass `-c` then `ghcid` will pass `-j` and things will load in parallel. You can see the command used on the first line when ghcid starts up, e.g.

```
C:\Neil\hlint>ghcid
Loading ghci -fno-code -fno-break-on-exception -fno-break-on-error -v1 -ferror-spans -j ...
```

**Comment by ChShersh** [comment]
@ndmitchell Thanks for quick answer! That completely resolves my question.
