### ISSUE TITLE
Is it possible to support auto-complete?

### ISSUE THREAD

**Issue by zhu-fei** [ndmitchell/ghcid#178]
Ghci support auto completion, so there is some way for ghcid to support auto completion just by ghci, am I right?

**Comment by ndmitchell** [comment]
Ghci supports it, yes. But ghcid doesn't integrate with any IDE's directly, so there's no way to surface the completions. You could build ghcid into a more complete IDE LSP experience, but then is ghcid itself adding anything? If not, then https://marketplace.visualstudio.com/items?itemName=dramforever.vscode-ghc-simple is the direction to go - that tries to build on VS Code direct with Ghci completions. (I haven't tried that project yet, but its on my todo list!)

**Comment by zhu-fei** [comment]
For example ,  using stack Ghci to load a project, when you edit a file (let's say Main.hs) , you can send `:module Main `command, and then user type character "i",  can we just simulate i + "tab key" to ghci to collect all the possible completions ?  How to integrate to IDE is another problem, I don't want to consider it for now.
