### ISSUE TITLE
Possible to generate haddocks via ghcid?

### ISSUE THREAD

**Issue by saurabhnanda** [ndmitchell/ghcid#189]
I'm trying to find a fast workflow for rapidly iterating while writing haddock documentation, but everything seems too slow. Context: https://stackoverflow.com/questions/51530084/getting-stack-to-build-only-haddock-docs-and-not-the-library-executable

Is it possible to generate haddocks via ghcid so that changing docs in one file don't trigger a full project build and then a full haddock build?

**Comment by ndmitchell** [comment]
Not that I know - unfortunately Haddock is not incremental - it has to run in it's entirety. If you are finding that `cabal haddock` first compiles your library, you might be able to run `haddock` directly, which won't compile (or at least, has more chance of doing less).

**Comment by saurabhnanda** [comment]
@ndmitchell I know this question is no longer related to ghcid now, so let me know if I should take it elsewhere.

Do you know how to make `haddock` aware of the stack packageDB such that it can resolve references to other modules when it is generating docs for a single file?

**Comment by ndmitchell** [comment]
@saurabhnanda I suggest taking it to the stack GitHub or stackoverflow, because I doubt anyone watching here will have any ideas. Closing here as I suspect it won't help you with answers.
