### ISSUE TITLE
(Option for) colored output

### ISSUE THREAD

**Issue by I3ck** [ndmitchell/ghcid#193]
I think it would be nice to have some of the output highlighted with color.  
E.g. filename, error in file, line number.  
Rust does something similar:  
https://blog.rust-lang.org/images/2016-08-09-Errors/new_errors4.png

**Comment by ndmitchell** [comment]
Newer versions of ghcid, coupled with newer versions of GHC, already do this.

![image](https://user-images.githubusercontent.com/1651197/44219320-a10b8d80-a173-11e8-9b7e-ac3f43dbd3c6.png)

Or did you have something else in mind?

**Comment by I3ck** [comment]
perfect, time to upgrade then :)
