### ISSUE TITLE
Attempting to get terminal with results in odd `NTERNAL_GHCID.putStrLn` errors

### ISSUE THREAD

**Issue by afcowie** [ndmitchell/ghcid#197]
Hey,

Attempting to use System.Console.ANSI `getCursorPosition`, `setCursorPosition` (to do the dance to find out the width of the terminal) but when run in _ghcid_ the following comes out:

```
<interactive>:24:1-22: error:
    Not in scope: ‘NTERNAL_GHCID.putStrLn’
    Perhaps you meant one of these:
      ‘INTERNAL_GHCID.putStrLn’ (imported from System.IO),
      ‘INTERNAL_GHCID.hPutStrLn’ (imported from System.IO),
      ‘INTERNAL_GHCID.putStr’ (imported from System.IO)
    No module named ‘NTERNAL_GHCID’ is imported.

```
at the end of the program run, which is just weird on all kinds of levels. (It works when built as a binary and run independently in a shell.) There was also a `^[[41;1R` that appeared on the console a few lines earlier.

Not sure that this is your problem in any way whatsoever, but I thought I should mention it.

AfC

P.S. Do you know a way to get terminal width?

**Comment by afcowie** [comment]
The code I'm running is
```haskell
getConsoleWidth :: IO (Int)
getConsoleWidth = do
    pos <- getCursorPosition 
    case pos of
        Just (row, col) -> do
            setCursorPosition 999 999
            pos' <- getCursorPosition  -- bottom right
            setCursorPosition row 0
            case pos' of
                Just (height, width) -> do
                    return width
                Nothing -> return 80
        Nothing         -> return 99
```
In _ghcid_ I get `99` back when I run that right after startup. But as a binary I get the correct current terminal width.

(this is the trick used by the _resize_ command, apparently.

**Comment by ndmitchell** [comment]
If you are moving the cursor while ghcid is sending commands to it I imagine you are messing up the output and ghcid is getting bust as a result?

Ghcid already gets the size of the terminal using https://hackage.haskell.org/package/terminal-size-0.3.2.1/docs/System-Console-Terminal-Size.html - I suggest just using that.

**Comment by afcowie** [comment]
Interesting. Didn't know about that one.

fwiw, calling its `size` inside ghcid results in `Nothing`. Weird. Oh well. It _does_ work as advertised when built as a binary. Thanks for the suggestion. I'll use it in preference to the ANSI hack (and accept that it'll be a bit unavailable in **ghcid** sessions).
