### ISSUE TITLE
Is it possible to add doctest support?

### ISSUE THREAD

**Issue by wizzup** [ndmitchell/ghcid#200]
Currently I am running `doctest` every time when my source file is saved. (I use vim write file trigger)
It would be nice if `ghcid` also run `doctest` when file is changed.

`ghcid` only run once and exit when I try  `ghcid --command 'doctest source.hs' `

**Comment by wizzup** [comment]
`ghcid --command 'cabal new-repl' --test ':!doctest source.hs'` also doesn't work.

Some error is reported but I can't read because the screen keep flickering.

**Comment by ndmitchell** [comment]
The first of those strings definitely won't work - the command has to be what you use to start ghci. The second looks plausible - does it work if you omit the `--test`? Can you hit Ctrl-C in the terminal and thus find out what the error is?

**Comment by wizzup** [comment]
I am trying with [data61 fp-course](https://github.com/data61/fp-course)

`ghcid --command 'cabal new-repl'` seem working. if my code failed to compile it will give the error. if my code is compiled it give me this
~~~
All good (27 modules, at 08:24:27) 
~~~
but it also give
~~~
Reloading...                                                                                                                                                                                           
  Error when waiting, if this happens repeatedly, raise a ghcid bug.                                                                                                                                   
  "/data/learn/haskell/fp-course/(0.01 secs, 763,864 bytes)/src/": can't watch what isn't there!: does not exist  
~~~

----
For `ghcid --command 'cabal new-repl' --test ':!doctest src/Course/MoreParser.hs'`
it give the same error above and `Interrupted`

~~~
Interrupted.

All good (27 modules, at 08:31:29)
Running test...
~~~

But the `doctest` didn't work. it should report some failed test.

For example, If i run `cabal new-repl` from bash prompt and `:!doctest ` in repl's prompt I got this
~~~
λ> :!doctest src/Course/MoreParser.hs
Loaded package environment from /data/learn/haskell/fp-course/.ghc.environment.x86_64-linux-8.4.3
Loaded package environment from /data/learn/haskell/fp-course/.ghc.environment.x86_64-linux-8.4.3
src/Course/MoreParser.hs:268: failure in expression `parse hexu "u0010"'
expected: Result >< '\DLE'
 but got: *** Exception: todo: Course.MoreParser#hexu
          CallStack (from HasCallStack):
            error, called at src/Course/MoreParser.hs:285:3 in main:Course.MoreParser
~~~

**Comment by ndmitchell** [comment]
Problem is you have `+s` in a `.ghci` file somewhere. I fixed that as part of #162, but hadn't made a release since I was planning to do more changes, but got delayed. I've now made a release so 0.7.1 should fix it.

**Comment by wizzup** [comment]
I create a minimum testing code for this [here](https://github.com/wizzup/ghcid-doctest)

`doctest` is run correctly but doesn't stop on error. `ghcid` keep running nonstop

Also I comment `+s` out from my `.ghci`

```
$ ghcid --command 'cabal new-repl' --test ':!doctest Main.hs'
Loading cabal new-repl ...
Build profile: -w ghc-8.4.3 -O1
In order, the following will be built (use -v for more details):
 - ghcid-doctest-0.1.0.0 (exe:ghcid-doctest) (ephemeral targets)
Preprocessing executable 'ghcid-doctest' for ghcid-doctest-0.1.0.0..
GHCi, version 8.4.3: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /data/works/dotfiles/_ghci
[1 of 1] Compiling Main             ( Main.hs, interpreted )
Ok, one module loaded.
*Main
λ> *Main
λ> *Main INTERNAL_GHCID
it :: ()
it :: ()

All good (1 module, at 17:33:05)
Running test...

it :: ()
it :: ()
Loaded package environment from /home/wizzup/tmp/ghcid-doctest/.ghc.environment.x86_64-linux-8.4.3
Loaded package environment from /home/wizzup/tmp/ghcid-doctest/.ghc.environment.x86_64-linux-8.4.3
Main.hs:5: failure in expression `1 + 1'
expected: 1
 but got: 2

Examples: 1  Tried: 1  Errors: 0  Failures: 1

...done

Reloading...
  Error when waiting, if this happens repeatedly, raise a ghcid bug.
  "/home/wizzup/tmp/ghcid-doctest/it :: ()/": can't watch what isn't there!: does not exist


All good (1 module, at 17:33:06)
Running test...
```

**Comment by ndmitchell** [comment]
What is causing `it :: ()` to appear at the end of each line? That's going to be the problem. I suspect it's your `.ghci` at fault, which you haven't put in the repo for the bug.

**Comment by wizzup** [comment]
Thanks for the new release. I just test version 0.7.1 and it is is working.

* `doctest` now stop at the first error
* no more reloading error
* I can now use `+t` and `+s` in my `.ghci`
