### ISSUE TITLE
GHC 8.0.1 issue

### ISSUE THREAD

**Issue by LeventErkok** [ndmitchell/ghcid#206]
Unfortunately I'm still stuck with GHC 8.0.1 at work, and ghcid is failing to start:

```
$ ghcid --version
Auto reloading GHCi daemon v0.7.1
$ ghcid
Loading ghci -fno-code -fno-break-on-exception -fno-break-on-error -v1 -ferror-spans -j ...
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/lerkok/.ghci
Loaded GHCi configuration from /home/lerkok/.ghci
Some flags have not been recognized: -fno-hide-source-paths

No files loaded, GHCi is not working properly.
Command: ghci -fno-code -fno-break-on-exception -fno-break-on-error -v1 -ferror-spans -j
```

I understand `-fno-hide-source-paths` is only available past 8.2; is there a way `ghcid` can check for the GHC version and not issue it if it's an ancient one?

**Comment by ndmitchell** [comment]
Note that no hide source paths isn't on the initial command line - it's passed using :set which ignores unknown flags. I don't think that's the problem. I also test with GHC 8.0, so it is fully supported.

If you run the ghci line does it drop you into a prompt with appropriate files loaded?

**Comment by LeventErkok** [comment]
Quite right; I botched my .ghci file and didn't realize. My apologies.
