### ISSUE TITLE
how to run a Hspec test suite

### ISSUE THREAD

**Issue by pcarbonn** [ndmitchell/ghcid#208]
I checked #128, but it does not fully solve the problem.

When I run `ghcid "--command=stack ghci H-Calc:spec" "--test=:main"`, it runs my test set correctly, and again correctly when I change the code of my test suite, but NOT if I change the code of my main project.  

Ghcid seems to track the `test` folder, but not the `src` folder.

My project is [on github](https://github.com/pcarbonn/H-Calc), so you can see the file structure and cabal file.

**Comment by moodmosaic** [comment]
You might want to check out *Run your test suite on every edit* section of [this](http://www.parsonsmatt.org/2018/05/19/ghcid_for_the_win.html) post by @parsonsmatt.

**Comment by pcarbonn** [comment]
OK. Thanks !

**Comment by chrissound** [comment]
Is there a solution for this with cabal as well?

```
ghcid --command='cabal v2-repl lib:orgmode-parse test:tests' --test 'Main.main'
Loading cabal v2-repl lib:orgmode-parse test:tests ...
cabal: Cannot open a repl for multiple components at once. The targets
'orgmode-parse' and 'tests' refer to different components..

The reason for this limitation is that current versions of ghci do not support
loading multiple components as source. Load just one component and when you
make changes to a dependent component then quit and reload.

Command "cabal v2-repl lib:orgmode-parse test:tests" exited unexpectedly with error message: 
```

**Comment by ndmitchell** [comment]
The underlying issue is a limitation in GHC, which is being addressed by a summer-of-code project as we speak. Cabal chooses to take that limitation and make it a fatal error. Stack chooses to continue, accepting things might not work. But I don't believe there's much to be done with Cabal, other than talking to the Cabal maintainers, or waiting for a GHC with multi-component support.

**Comment by tfc** [comment]
> is being addressed by a summer-of-code project as we speak

is there any progress by now?

**Comment by Ericson2314** [comment]
The work has not been completely merged, but stepping stones written by @fendor and also @hsyl20 have. Rest assured we will get there!

**Comment by sekunho** [comment]
Just checking in. Is there a workaround/solution for `cabal repl` that I missed somehow?

**Comment by ndmitchell** [comment]
@sekunho - if you are referring to the issue of loading src and test at once, then I don't think it's fully merged yet, but I'm not sure.

**Comment by gabrielsimoes** [comment]
This is now possible with cabal-head, e.g. for ghcup:
` ` ` 
ghcup install cabal -u https://github.com/haskell/cabal/releases/download/cabal-head/cabal-head-Linux-x86_64.tar.gz head
` ` `
until https://github.com/haskell/cabal/pull/8726 makes into a release (probably 3.12 from the milestones). 

This allows something like:

` ` ` 
ghcid --command='cabal v2-repl --enable-multi-repl test:tests lib:orgmode-parse' --test 'Main.main'
` ` `
