### ISSUE TITLE
Fails to detect certain load failure messages

### ISSUE THREAD

**Issue by thomie** [ndmitchell/ghcid#21]
When I delete the file being monitored, or if it didn't exist to begin with, `ghcid` always reports "All good". This is confusing, because it hides the fact something is probably wrong.

I'm using version `0.3.2` and the command `ghcid --command='ghci GHCidTest.hs' ` on Ubuntu Linux.

**Comment by ndmitchell** [comment]
I think robustly detecting all the variants is too hard, so I changed it to detect no files loaded at the start and then quickly exit, without hiding the error messages that ghci almost certainly already gave you. That makes the experience in these cases almost as good as if I'd actually caught the error.
