### ISSUE TITLE
Variable not in scope: main when using other-modules and --test=:main

### ISSUE THREAD

**Issue by dnadales** [ndmitchell/ghcid#216]
I have a cabal file that looks as follows:

```haskell
test-suite my-test
  hs-source-dirs: test
  main-is: test.hs

  other-modules: SomeModuleUsedInTest
```

If I try to run:

```sh
ghcid -c  \"cabal new-repl my-test\" --test=:main" 
```
The I get the following error:

```text
<interactive>:23:53-56: error:
    • Variable not in scope: main :: IO a0
    • Perhaps you meant ‘min’ (imported from Prelude)
```

By removing the `other-modules` everything works again.

Any idea what might be causing this behaviour?

**Comment by ndmitchell** [comment]
If you do `cabal new-repl my-test` and then type `:main` what happens? I'd try getting `ghcid` out of the picture first.

**Comment by dnadales** [comment]
*Ledger.Delegation.Examples> :main

<interactive>:1:53: error:
    • Variable not in scope: main :: IO a0
    • Perhaps you meant ‘min’ (imported from Prelude)
*Ledger.Delegation.Examples>

**Comment by dnadales** [comment]
So it seems this might be a problem with `cabal` which doesn't bring `Main` into scope...

**Comment by ndmitchell** [comment]
No idea I'm afraid. I stick to a .ghci in each repo as that's the simplest solution for me.
