### ISSUE TITLE
ghcid reports "can't find file" while editing with Vim

### ISSUE THREAD

**Issue by thomie** [ndmitchell/ghcid#22]
While editing a file with `Vim`, `ghcid -v` reports:

```
%WAITING: GHCidTest.hs

Reloading...
  GHCidTest.hs
%GHCINP: :reload
%GHCERR: 
%GHCERR: <no location info>: can't find file: GHCidTest.hs
%GHCOUT: #~GHCID-START~##~GHCID-START~#Failed, modules loaded: none.
%GHCOUT: #~GHCID-START~##~GHCID-FINISH~#
%GHCERR: *** Exception: #~GHCID-FINISH~#
%GHCINP: :show modules
%GHCOUT: #~GHCID-START~##~GHCID-START~##~GHCID-START~##~GHCID-FINISH~#
%GHCERR: *** Exception: #~GHCID-FINISH~#
%ACTIVE: []
%LOAD: []

All good

%WAITING: 
```

It only happens with `Vim`, not with other editors, and only after a few edits have been made (and for which `ghcid` did report errors and warnings correctly). I'm not sure it's a ghcid bug, it might be something specific to my system.

See also #21.

I'm using version 0.3.2 and the command `ghcid --command='ghci GHCidTest.hs'` on Ubuntu Linux.

**Comment by ndmitchell** [comment]
I think I've found the culprit, so I'm going to assume this is closed. If not, please comment on #28 (which I think had the same underlying cause).
