### ISSUE TITLE
(neovim plugin) buffer hiding behavior

### ISSUE THREAD

**Issue by goolord** [ndmitchell/ghcid#220]
How do you get he behavior seen in this gif, where the ghcid buffer is only open when there is an error?
![IMG](https://raw.githubusercontent.com/cloudhead/images/master/neovim-ghcid.gif)
I've tried setting combinations of `g:ghcid_keep_open` `g:ghcid_background` but neither of these worked.
Also: should this behavior be the default?

**Comment by goolord** [comment]
more info (using nightly nvim build)
```
> nvim -v
NVIM v0.4.0-91-gea7504cf8
Build type: RelWithDebInfo
> ghcid --version
Auto reloading GHCi daemon v0.7.1
```
`commit a605d8c4571d9ed4340ba3f4dc3effba8097b61a (origin/master, origin/HEAD)`

**Comment by ndmitchell** [comment]
CC @cloudhead who probably knows best

**Comment by cloudhead** [comment]
This is the default behavior, if your vim has `hidden` set, the relevant setting is `g:ghcid_keep_open` which you'll want *off*:

```
if !exists("g:ghcid_keep_open")
  let g:ghcid_keep_open = !&hidden
endif
```

So as you can see, it is by default set to the inverse of `&hidden`.

**Comment by goolord** [comment]
in that case maybe i'm experiencing a bug, even with a minimal vim configuration and ghcid being the only plugin the ghcid buffer persists
![IMG](http://i.imgur.com/2yrojAW.png)

**Comment by cloudhead** [comment]
`hidden` is off by default, so you'd have to have `set hidden` in your config for it to work.

**Comment by goolord** [comment]
oh, ok. thanks for taking the time to help
