### ISSUE TITLE
Longer errors get cut off

### ISSUE THREAD

**Issue by domenkozar** [ndmitchell/ghcid#222]
When using servant and it's famous longer errors, they get cut off after ~7 lines

**Comment by ndmitchell** [comment]
Which ghcid version? I know this used to be true with older ghcid, but I thought I changed that some time ago. If you still get it with the latest ghcid, a way to reproduce would be handy, e.g. how to provoke a huge error message.

**Comment by domenkozar** [comment]
I've looked into this, seems like something else is cutting them off. I'll reopen if I manage to prepare a reproducible example.
