### ISSUE TITLE
Make ghcid friendly for emacs compile buffers

### ISSUE THREAD

**Issue by codygman** [ndmitchell/ghcid#224]
I would like to use the emacs compile buffer for ghcid. The biggest reason being the compile buffer parses the `filepath:filenumber` output from ghcid and lets you navigate the errors received by clicking or using a `next-error` function. I have two problems though:

1. This could be on the emacs side. I'm sure ghcid devs would know if it's responsible: Sometimes if the filepath is very long, it's wrapped to the width of the terminal and it shows up as:

```
/the/complete/path/to/

the/file
```

This breaks the line parsing/error navigation.

2. The compile buffer works by following the end of the content, but the newlines inserted after the errors means I'm shown a blank buffer and have to scroll up to the errors. This is similar to #167.

From a ghcid maintainer perspective, it may be that neither of these things are worth accommodating. However it seems to me without a lot of context it would be pretty easy to add config flags or options for not line wrapping and not adding whitespace after each run.

But maybe I just need to use something like `stack build --fast --filewatch` instead or write some elisp to just make things work.

**Comment by ndmitchell** [comment]
Happy to accommodate, but I don't use emacs, so you'll need to describe how to fix or improve things. I just pushed something to HEAD which switches to not inserting line breaks where it detects that things run off the end of the screen, hopefully that fixes number 1.

I don't really understand number 2, but patches welcome!

**Comment by codygman** [comment]
It looks like that fixed the issue of going way past in the Emacs compilation buffer as well as the filenames issue. Thank you!

If you have this issue, also worth making sure you `(setq compilation-scroll-output t)` instead of `nil` or `'first-error`.
