### ISSUE TITLE
Polling ignores requested frequency

### ISSUE THREAD

**Issue by brprice** [ndmitchell/ghcid#226]
The polling logic seems odd: we wait for the requested time only on the first iteration (in `waitFiles`) after each reload, and each subsequent one (in `recheck`) it waits a fixed 0.1.

I suspect that we should sleep in `WaiterPoll` branch of `recheck`'s case.

I wonder if this is related to #182?

**Comment by ndmitchell** [comment]
#182 wasn't using polling, so shouldn't be related. You would also have seen the 0.1s blips in the CPU graph if it was sleeping.

Reading the code carefully I think you're spot on though. There are two WaiterPoll branches, and I think they're the wrong way round 🤦‍♂️ .  The corresponding WaiterNotify branch is first immediate, and then sleeping, so now I made WaiterPoll match that.
