### ISSUE TITLE
ghcid stuck in submodule

### ISSUE THREAD

**Issue by cdupont** [ndmitchell/ghcid#229]
I have a project with several git submodules.
It seems that ghcid is stuck in on of the submodules:
```
$ pwd
/home/cdupont/Documents/Waziup/Platform/servant
$ ghcid
blabla...
28 | import qualified Data.Text as T
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/cdupont/Documents/Waziup/Platform/servant/aesonbson/Data/AesonBson.hs:45:8-15: warning: [-Wname-shadowing]
    This binding for ‘exponent’ shadows the existing binding
      imported from ‘Prelude’ at /home/cdupont/Documents/Waziup/Platform/servant/aesonbson/Data/AesonBson.hs:14:8-21
      (and originally defined in ‘GHC.Float’)
   |
45 |        exponent       = Scientific.base10Exponent n
   |        ^^^^^^^^
```
And nothing else appears. 
"aesonbson" is the submodule, while "servant" is my project.
Even if I change files in my main project, it doesn't recompile.
My project is here: https://github.com/cdupont/Waziup-API-HS

**Comment by ndmitchell** [comment]
Can you run with `--verbose` and share the full output? That will tell us what `ghcid` is waiting on, and then either the problem is that it doesn't trigger on a file it changes, or it isn't waiting for a file it should.

**Comment by cdupont** [comment]
Sure!
```
/home/cdupont/Documents/Waziup/Platform/servant/aesonbson/Data/AesonBson.hs:45:8-15: warning: [-Wname-shadowing]
    This binding for ‘exponent’ shadows the existing binding
      imported from ‘Prelude’ at /home/cdupont/Documents/Waziup/Platform/servant/aesonbson/Data/AesonBson.hs:14:8-21
      (and originally defined in ‘GHC.Float’)
   |
45 |        exponent       = Scientific.base10Exponent n
   |        ^^^^^^^^



%WAITING: /home/cdupont/Documents/Waziup/Platform/servant/.ghcid ./stack.yaml /home/cdupont/Documents/Waziup/Platform/servant/waziup.cabal /home/cdupont/Documents/Waziup/Platform/servant/.ghci /home/cdupont/Documents/Waziup/Platform/servant/aesonbson/Data/AesonBson.hs /home/cdupont/Documents/Waziup/Platform/servant/aesonbson/test/Main.hs
%WAITING: /home/cdupont/Documents/Waziup/Platform/servant /home/cdupont/Documents/Waziup/Platform/servant/aesonbson/Data /home/cdupont/Documents/Waziup/Platform/servant/aesonbson/test
```
It seems to be waiting on some files in the submodule, but not on the files in the main module.

**Comment by cdupont** [comment]
Here is the full output: https://gist.github.com/cdupont/08f14a9f89974482f7a6e4c4b35057ac

**Comment by ndmitchell** [comment]
It only waits on the files it loads. Can you include the full output from `--verbose`? Probably as a gist.

**Comment by cdupont** [comment]
The full output is here: https://gist.github.com/cdupont/08f14a9f89974482f7a6e4c4b35057ac

**Comment by ndmitchell** [comment]
Which file do you think it should be waiting on that it isn't? It has only loaded 2 files, from aesonbson. But if you do `stack ghci --test --bench --no-load --ghci-options=-fno-code --ghci-options=-fno-break-on-exception --ghci-options=-fno-break-on-error --ghci-options=-v1 --ghci-options=-ferror-spans --ghci-options=-j` then stack will only load those 2 files. You first have to get `ghci` working as you want, before `ghcid` can take over.

**Comment by cdupont** [comment]
I get the same result with the stack command.
If I remove the "--test" from it, it works:
```
stack ghci --bench --no-load --ghci-options=-fno-code --ghci-options=-fno-break-on-exception --ghci-options=-fno-break-on-error --ghci-options=-v1 --ghci-options=-ferror-spans --ghci-options=-j
```
With this option, all the files are taken into account.

Does that mean I have some issues in the way my tests are defined? Actually I don't have tests in my main module, but the submodule have them.

**Comment by ndmitchell** [comment]
You can pass `-c` to `ghcid` to say what command to use. I recommend one that drops `--test`. As to why `stack ghci` with `--test` does less than without, I have no idea - that seems odd... I tend to always hand-craft `.ghci` files to choose how to load stuff.

**Comment by cdupont** [comment]
Can I put the command in the .ghci? or some config file?

**Comment by ndmitchell** [comment]
Yes, see https://github.com/ndmitchell/ghcid#usage-tips

**Comment by cdupont** [comment]
Wonderful, thanks.
