### ISSUE TITLE
addWatch: resource exhausted (No space left on device)

### ISSUE THREAD

**Issue by cdupont** [ndmitchell/ghcid#233]
I have the error in the title:
```
Error when waiting, if this happens repeatedly, raise a ghcid bug.
addWatch: resource exhausted (No space left on device)
```
There is plenty of disk space.
Should I raise some ulimit?

**Comment by ndmitchell** [comment]
Probably, although I have no idea what. File handles is usually a good bet on a Mac.

**Comment by cdupont** [comment]
I could not find the correct ulimit to raise. However I closed another processe that consumed a lot of files and the error was gone.

**Comment by sukwon0709** [comment]
Just for anyone facing the same problem:
`sudo sysctl -w fs.inotify.max_user_watches=262144`
fixed the issue for me.

**Comment by ndmitchell** [comment]
Thanks, I copied this information into the README.

**Comment by drewboardman** [comment]
> Just for anyone facing the same problem:
> `sudo sysctl -w fs.inotify.max_user_watches=262144; sudo sysctl -p`
> fixed the issue for me.

I get `sysctl: cannot open "/etc/sysctl.conf": No such file or directory` with that.
