### ISSUE TITLE
Error if no/partial prelude

### ISSUE THREAD

**Issue by Duta** [ndmitchell/ghcid#24]
I'm in a hurry, so I'm afraid this won't have much detail.
When either using -XNoImplicitPrelude or `import Prelude (a, few, functions)`, ghcid gets stuck.

**Comment by ndmitchell** [comment]
A test case, if I ever need them again:

    import Prelude(print)
    main = print 1

And running with `--verbose` shows that it can't find `putStrLn` or `error`. I've made them qualified and it now works. I've released 0.3.6 including this fix.

**Comment by ndmitchell** [comment]
Thanks for the bug report btw, very easy to replicate from your notes!
