### ISSUE TITLE
ghcid fails to start with an invalid argument error

### ISSUE THREAD

**Issue by coot** [ndmitchell/ghcid#244]
``
ghcid --verbose -c "cabal new-repl lib:some-package

...
Ok, 40 modules loaded.
%STDOUT: *Ouroboros.Network.AnchoredFragment> *Ouroboros.Network.AnchoredFragment> *Ouroboros.Network.AnchoredFragment INTERNAL_GHCID> *Ouroboros.Network.AnchoredFragment INTERNAL_GHCID> #~G
HCID-START~##~GHCID-START~##~GHCID-START~##~GHCID-START~##~GHCID-START~##~GHCID-FINISH-1~#
ghcid: fd:16: hGetLine: invalid argument (invalid byte sequence)
```

```
ghcid --version
Auto reloading GHCi daemon v0.7.2
```

This error is specific to the package, on other packages it works fine for me.  `cabal repl lib:some-package` works just fine.

**Comment by ndmitchell** [comment]
My guess is there's a UTF8 or ASCII thing, and that somehome ghcid is reading a non-ascii byte. What is your LOCALE setting? Your OS? Does `cabal new-repl lib:some-package` spit out any non-ascii characters or anything funky looking? I suspect it can be solved by setting the encoding on the streams, but not sure to what. Binary is always my first attempt.

**Comment by coot** [comment]
Thanks @ndmitchell, I'll close this as the error went away; I didn't had a chance to bisect what fixed or weather there were some non-ascii chars in the output.

**Comment by ndmitchell** [comment]
Thanks @coot - let me know if it recurs.

**Comment by Benjmhart** [comment]
@ndmitchell - I'm finding this error when my `LC_ALL` is set to `en_US.UTF-8`,  however if i set LC_ALL to C, the problem vanishes.

**Comment by ndmitchell** [comment]
@Benjmhart the complete output of `--verbose` when it both works with C locale and fails with UTF8 locale would be very interesting. Are you using `--test`?

**Comment by Benjmhart** [comment]
no, but i am using `--allow-eval` though i tried removing that flag and still got the error i believe

i will take a look tonight
