### ISSUE TITLE
Using ghcid with a happy+alex based project

### ISSUE THREAD

**Issue by LeventErkok** [ndmitchell/ghcid#256]
I've a project where I've a `.x` (for alex) and `.y` (for happy) files. Cabal handles this combo just fine.

But if I'm running `ghcid` on it and make a change to `.y` or `.x` file, ghcid is obviously not triggered since the corresponding `.hs` files are only modified during a `cabal build` call. Would be great if this was automatically handled.

Am I asking for too much? Obviously this is not a huge showstopper; as I can run cabal separately and `ghcid` then picks up the changes, but it sort of beats the whole point of tight integration. I'm not necessarily asking for supporting this scenario, but if there's a "trick" to make it work, I'd love to hear it!

**Comment by ndmitchell** [comment]
You should be able to give the .x etc files to --restart then if those files change it will kill ghci, and run Cabal build again. The other option is to use something like steel overseer https://github.com/schell/steeloverseer to run Cabal build and then ghcid will pick up the changes that way. If you try both I'd be keen to know which works best and put it in the readme.

**Comment by LeventErkok** [comment]
`restart` option seems to work well enough. Thanks!

**Comment by ndmitchell** [comment]
Thanks, I've added it to the README at https://github.com/ndmitchell/ghcid/blob/master/README.md#i-use-alex-x-and-happy-y-files-how-can-i-check-them

**Comment by vyorkin** [comment]
Is there a way I can ask `ghcid` to watch for **all** `.y` and `.x` files in a given directory and its subdirectories?

**Comment by ndmitchell** [comment]
You can detect when a directory and its subdirectories changes, or a specific file. There's currently no way to say just .y files in a directory - but the only issue with that is restarting more than it needs (which is pretty fatal if that's your main source directory).
