### ISSUE TITLE
ghcid.cabal ghc-options

### ISSUE THREAD

**Issue by dciug** [ndmitchell/ghcid#258]
Is there a reason why `ghc-options` specifies the `-main-is` flag? Isn't it redundant given the `main-is `option from cabal itself?

**Comment by ndmitchell** [comment]
Easiest way to confirm is remove it and see if it still builds. The Cabal main-is lets you say the filename. The GHC main-is lets you say the module name if it's not Main. I think Cabal screwed up by being file name orientated, but hey ho...

**Comment by dciug** [comment]
Understood. Just tried it with `cabal new-build` and it fails. So it has to stay.

**Comment by ndmitchell** [comment]
Thanks for checking
