### ISSUE TITLE
Excessive wakeups

### ISSUE THREAD

**Issue by afcowie** [ndmitchell/ghcid#26]
_powertop(8)_ on Linux reports the most expensive process in terms of processor wakups is _ghcid_.

```
     Usage     Events/s     Category       Description
  4.5 ms/s     108.8        Process        ghcid --command=cabal exec ghci tests/Experiment.hs
```
this represents about a quarter of the user-space power draw on this machine when on battery!

Originally I thought you were using _inotify(7)_ so assumed that it wouldn't be doing any wakeups at all. When I saw it sucking down power like this, I had a look and just realized you're **not** using [hnotify](http://hackage.haskell.org/package/hinotify). Oh.

Is that deliberate? Assuming not, would you countenance a dependency on [fsnotify](http://hackage.haskell.org/package/fsnotify) (which purports to be a cross-platform wrapper around the different filesystem notification mechanisms)?

AfC

**Comment by ndmitchell** [comment]
I have issues with ghcid on battery power too. Depending on fsnotify is fine, but last time I tried on windows it failed. I'll try again tomorrow.

**Comment by ndmitchell** [comment]
My reports of it not working are at https://github.com/haskell-fswatch/hfsnotify/issues/50. I suggest the right thing to do is add an abstraction layer in ghcid, and an option to use either notify or polling. We can give a flag for the alternatives, and if it seems not to work robustly, default to polling on Windows.

**Comment by afcowie** [comment]
I'd agree with that. 'hnotify' exposes a lot more of inotify, and given how many corner cases there are  (c.f. http://blogs.operationaldynamics.com/andrew/software/haskell/rebuilding-via-inotify ) hiding that breadth of features behind a lowest common denominatior abstraction layer always worries me. For instance, inotify can watch files or a directory for a wide range of events whereas 'fsnotify' only talks about directories.

**Comment by ndmitchell** [comment]
I was thinking of the abstraction layer being based on what ghcid needs, not what the notify thing provides. I want to wait for a list of files, so one API could be:

    waitCreate :: IO Waiter
    waitFor :: Waiter -> [FilePath] -> IO [FilePath]

Create a `Waiter` object, given that object, wait for some files and return which ones changed. That should map to all reasonable abstractions and make the most of them all.

**Comment by ndmitchell** [comment]
All done, just broken, so dealing with that in the next ticket.
