### ISSUE TITLE
Add a way to customize the shown `--test` message

### ISSUE THREAD

**Issue by asterite** [ndmitchell/ghcid#260]
Right now when you run `ghcid` with `--test=...` it shows:

```
Running test...
```

just before the "test" is run.

In our case we are starting a web server in `--test`, so seeing "Running test..." just before bringing up the web server (which might take a while) is a bit strange. Also, for developers joining our project and running our shake commands we have to explain them "This is not actually running any test".

Do you think it would be a good idea to customize this message? It could be something like `--test-message="Starting web server..."`. I know it might feel a bit redundant to pass a message to be shown right next, but it makes sense if the command runs as part of other commands.

**Comment by ndmitchell** [comment]
To me, the value seems marginal, but given it seems a pain point for you, and the ongoing maintenance cost should be pretty tiny, I'm happy to take a patch. Exactly as you describe seems reasonable.

**Comment by asterite** [comment]
@ndmitchell Great! And thanks for the super fast reply. I will work on a patch then, though I'm not sure how to compile the project (but I can try to figure that out).

**Comment by ndmitchell** [comment]
`cabal install` or `stack install` should be sufficient. You can also `ghcid` to develop it (that's how I do it).
