### ISSUE TITLE
Version 0.7.4 no longer detects terminal resizes

### ISSUE THREAD

**Issue by tombusby** [ndmitchell/ghcid#263]
I've replicated this on my mac and my linux machine. Versions `0.7.2` and `0.7.3` will properly detect when the terminal is resized, but `0.7.4` fails to do so.  It correctly detects the terminal size at start-up, but it seems to be impossible to force it to update, without stopping and restarting, in the latest version.

This means that if I run a `ghcid` instance, then later do a vertical split of the terminal in order to run another instance, then the type information for the original instance is pushed off the top; unless I stop and restart `ghcid`.

I'm going to hazard a guess that 9c47d9d63 is the cause. I'll have a look at this this evening if I get a mo.

**Comment by ndmitchell** [comment]
Oops! Just pushed a fix, will wait for it to go through CI and make a release. That patch was actually fine, but the subsequent https://github.com/ndmitchell/ghcid/commit/b7ada1174d33439f2ace785726e6ce902e7fc3ce#diff-1222cb420ac349a9902a5c31cd84c455R224 was a problem.

**Comment by ndmitchell** [comment]
0.7.5 now out

**Comment by tombusby** [comment]
@ndmitchell cheers will upgrade :)
