### ISSUE TITLE
No colors

### ISSUE THREAD

**Issue by ulysses4ever** [ndmitchell/ghcid#269]
GHC 8.6.5, ghcid 0.7.5 and no colors in gnome-terminal (Ubuntu 16.04). I seem to recall that they were there. Is it a known problem?

**Comment by ulysses4ever** [comment]
Okay, this is the problem only until first reload. Still, fills like a bug.

**Comment by DestyNova** [comment]
I get this when running `:Ghcid`; might be related?

```
Unknown flag: --color  
```

**Comment by ndmitchell** [comment]
See https://github.com/ndmitchell/ghcid/blob/master/README.md#i-only-see-source-spans-or-colors-on-errorswarnings-after-the-first-load and https://twitter.com/ndm_haskell/status/1159207825194856449?s=20 which gives the background. Known issue, and working as intended.

**Comment by ulysses4ever** [comment]
I see, thanks!
