### ISSUE TITLE
VS Code - ghcid plugin fails to start ghcid terminal

### ISSUE THREAD

**Issue by andrew-ni** [ndmitchell/ghcid#272]
When I press the command associated with `extension.startGhcid`, the ghcid terminal tries to open, but fails with this error notification: `The terminal shell path "ghcid" does not exist`

- `ghcid` command works when run from project root directory ('All good')
- `ghcid` is installed at **/Users/niandrew/.local/bin/ghcid**
- My $PATH is: `/Users/niandrew/.stack/programs/x86_64-osx/ghc-8.6.5/bin:/Users/niandrew/.local/bin:/Users/niandrew/.cabal/bin:/Users/niandrew/.ghcup/bin:/Users/niandrew/Library/Python/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

Am I doing something wrong here?

ghcid version:
```
Auto reloading GHCi daemon v0.7.5
```

VS Code info:
```
Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:22:37.660Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.7.0
```

**Comment by ndmitchell** [comment]
Does it work if you run `ghcid` in a VS Code terminal? Just start a default terminal in VS Code (View menu, Terminal) and type in `ghcid`. That's effectively what the extension does.

**Comment by ndmitchell** [comment]
@andrew-ni did you figure out what the issue was? Anything that could be done to make it easier, or fix the issue?
