### ISSUE TITLE
Mention `--allow-eval` in README

### ISSUE THREAD

**Issue by utdemir** [ndmitchell/ghcid#277]
I just learned it on a random conversation, and it was a huge time-saver for me; so thanks a lot for that feature.

However it was just by chance that I learned it, and even after that it took me a while to figure out how to use it (mainly which prefix to use). It'd be nice to have it mentioned on `README.md`, so more people can benefit from it.

**Comment by ndmitchell** [comment]
I was only the reviewer for the feature, @isovector contributed the implementation. Agreed it would be good to document. @isovector, so you want to suggest any text? Or alternatively, do you @utdemir want to suggest anything? Happy to take either a PR or a paragraph in this issue that I'll slot in the README.

**Comment by isovector** [comment]
I dunno. It just finds comments of the form `-- $> foo` and runs them as `foo` in the repl session. I stole the idea from [Unison](https://www.unisonweb.org/docs/tour/scratch-files) if you want to steal some of their documentation (search for `watch expression` in that link).

**Comment by jkeuhlen** [comment]
I'm not sure if it would be helpful to add any of it to the readme, but I decided to write up this blog post about the feature: https://jkeuhlen.com/2019/10/19/Compile-Your-Comments-In-Ghcid.html. I'd be happy to add any of that content or write up a smaller blurb on usage for the README if desired.

**Comment by ndmitchell** [comment]
Done in https://github.com/ndmitchell/ghcid/blob/master/README.md#evaluation
