### ISSUE TITLE
Make 'ghcid' work with 'clashi' (proposals)

### ISSUE THREAD

**Issue by martijnbastiaan** [ndmitchell/ghcid#282]
Over at https://github.com/clash-lang/clash-compiler we're building a Haskell to hardware compiler, Clash. Every program written in Clash is also a valid Haskell program, which basically means that we get a "Clash to x86" - therefore a "hardware simulator" - compiler for free. This means we can also use GHCi to build Clashi:

```
Clashi, version 1.1.0 (using clash-lib, version 1.1.0):
https://clash-lang.org/  :? for help
Clash.Prelude> 
```

`ghcid` doesn't currently work with clashi due to [it not recognizing the version string](https://github.com/ndmitchell/ghcid/blob/master/src/Language/Haskell/Ghcid.hs#L173). We could:

1. Add `Clashi, version ` to the list
2. Match on `[a-zA-z]+i, version ` instead
3. Launch the REPL processes with an environment flag set (`LAUNCHED_BY_GHCID=1`?) such that the process can output `ghcid` compatible strings

I'm willing to make a PR for any of these. Would any of these PRs be accepted?

**Comment by ndmitchell** [comment]
I'd certainly accept 1, and it seems the least effort, so I suggest we do that. Also happy with 3, if you think that's easier. I have minor concerns with 2, about spotting incorrect things as versions, so unless that's got other benefits, let's not do it now.

**Comment by ndmitchell** [comment]
I've made a release, v0.7.6, so you can use it installed.

**Comment by martijnbastiaan** [comment]
That's great! Thanks!
