### ISSUE TITLE
ghcid.el does not work in emacs 27.0.50 on nixos

### ISSUE THREAD

**Issue by codygman** [ndmitchell/ghcid#289]
I haven't tried on osx or ubuntu yet, but on nix the buffer shuts off. I did a bit of debugging and the invocation of start-process apparently looks like this:

```
(:name ghcid :buffer *ghcid* :command (/bin/sh -c stty -nl echo rows 16 columns 77 sane 2>/dev/null;if [ $1 = .. ]; then shift; fi; exec "$@" .. /bin/bash -c ghcid -c "stack ghci  --test --bench --ghci-options=-fno-code" -h 15
))
```

**Comment by ndmitchell** [comment]
CC @WraithM - I have no idea what this does, but other people have been maintaining it.

**Comment by wraithm** [comment]
CC @yoricksijsling - Any input here?

@codygman Could you provide more debugging info? I don't seem to have an issue on macOS in Emacs 26.

**Comment by codygman** [comment]
@wraithm I don't have issues so far in macOS with emacs 27.0.50 using stack either. I'll try posting more debug info on the failure when I'm at my NixOS box again.

**Comment by yoricksijsling** [comment]
The command that is given to `start-process` consists of two parts:
* `/bin/sh -c stty -nl echo rows 16 columns 77 sane 2>/dev/null;if [ $1 = .. ]; then shift; fi; exec "$@" ..` is added by term-mode. See here: https://github.com/emacs-mirror/emacs/blob/master/lisp/term.el#L1560
* `/bin/bash -c ghcid -c "stack ghci  --test --bench --ghci-options=-fno-code" -h 15` is produced by the ghcid mode. You should be able to run that from a terminal as well.

So far I've been using this with emacs 25.3, installed through apt on ubuntu 18.03. I gave it a quick go with emacs 26.3, stack and ghcid installed through nix and that seems to work fine. Here is the nix expression I used:

<details>

```nix
let
  pkgs = import <nixpkgs> { };
  myEmacs = pkgs.emacsWithPackages (epkgs:
    (with epkgs.melpaPackages; [
      # a whole list of packages
    ]));
in
with pkgs; [
  nix
  myEmacs

  # Haskell tools
  ghcid
  stack
]
```
</details> 

I'm not sure what nix expression to use to get emacs 27.0.50 running. If you have one for me I can give that a try as well.

**Comment by codygman** [comment]
Thank you for testing! Here is my nix expression:

```nix
with import <nixpkgs> {};

stdenv.lib.overrideDerivation (pkgs.emacs.override {
  srcRepo = true;
  withXwidgets = if (stdenv.isDarwin || "TRAVIS_OS_NAME" != "") then false else true;
}) (attrs: rec {
  name = "emacs-${version}${versionModifier}";
  imagemagick = pkgs.imagemagickBig;
  version = "27.0";
  versionModifier = ".50";

  doCheck = false;

  patches = null;

  configureflags = attrs.configureFlags ++ [
    "--with-harfbuzz"
    "--with-json"
  ];

  buildInputs = attrs.buildInputs ++ [
    harfbuzz
    jansson
  ];

  src = fetchFromGitHub {
    owner = "emacs-mirror";
    repo = "emacs";
    rev = "9cd3b50ca869e6a91668eb8bbc2a44617294b85c";
    sha256 = "0xdpyy04mik1bsib0x894gi1ib1w40s019kzqfvjjmqgsbvi7a9a";
  };
})```

You can import it like `myEmacs = import ./emacs.nix;`.

**Comment by codygman** [comment]
`/bin/bash` isn't correct on NixOS so had to update it like:

```shell
(term-exec (ghcid-buffer-name)
           ghcid-process-name
           (executable-find "bash")
           nil
           (list "-c" (ghcid-command height)))
```

An error is still happening though that isn't caught by `M-x toggle-*-on-error`.

**Comment by codygman** [comment]
This `term-exec` invocation is the cause of the error:

```
1 -> (term-exec "*ghcid*" "ghcid" "/run/current-system/sw/bin/bash" nil ("-c" "ghcid -c \"stack ghci --system-ghc --nix  --ghci-options=-fno-code\" -h 17
```

But I run this and it works fine:

```
stty -nl echo rows 100 columns 100 sane 2>/dev/null;\
if [ $1 = .. ]; then shift; fi; exec "ghcid"
> bash: [: =: unary operator expected
Loading stack ghci --test --bench --ghci-options=-fno-code --ghci-options=-fno-break-on-exception --ghci-options=-fno-break-on-error --ghci-options=-v1 --ghci-options=-ferror-spans --ghci-options=-j ...
Using main module: 1. Package `simple-haskell-project' component simple-haskell-project:exe:simple-haskell-project with main-is file: /home/cody/.emacs.d/testdata/simple-haskell-project/Main.hs
Building all executables for `simple-haskell-project' once. After a successful build of all of them, only specified executables will be rebuilt.
simple-haskell-project> initial-build-steps (exe)
Configuring GHCi with the following packages: simple-haskell-project
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
[1 of 1] Compiling Main             ( /home/cody/.emacs.d/testdata/simple-haskell-project/Main.hs, nothing )
Ok, one module loaded.
Loaded GHCi configuration from /run/user/1000/haskell-stack-ghci/3faf85ca/ghci-script
]0;All good, at 23:08:53 - simple-haskell-project
All good (1 module, at 23:08:53)
```

**Comment by codygman** [comment]
Also managed to get this from the *ghcid* buffer:

```
Could not read as type Int, "stack"
```

There is a chance you might need to add `--nix` to stack invocations like:

```
(format "stack ghci --system-ghc --nix %s --ghci-options=-fno-code" target)
```

**Comment by codygman** [comment]
```diff
diff -u /tmp/2 /tmp/1
--- /tmp/2	2019-12-04 23:54:18.950124815 -0600
+++ /tmp/1	2019-12-04 23:54:14.967175797 -0600
@@ -98,7 +98,7 @@
 
       (term-exec (ghcid-buffer-name)
            ghcid-process-name
-           "/bin/bash"
+           (executable-find "bash")
            nil
            (list "-c" (ghcid-command height)))
```

With just this change it's kind of working now but I get some odd terminal escape codes:

![screen02](https://user-images.githubusercontent.com/225847/70207860-8b680180-16f1-11ea-8d62-718af0bfbbcb.png)

**Comment by codygman** [comment]
I'm going to close this since that issue seemed transient and I've tested ghcid.el for a number of days now.
