### ISSUE TITLE
Running tests suite

### ISSUE THREAD

**Issue by cschneid** [ndmitchell/ghcid#29]
I have a test suite which I can run inside of `cabal repl test`, with a simple `main` call. 

Is there an existing way to make the test suite run every time I write a file?

**Comment by ndmitchell** [comment]
There is no such feature, but I have been expecting the request for a while, as it certainly seems a reasonable thing to add. My guess for the implementation:

* Take a `--test=command` flag (`--test=main` in your case).
* If you have a successful load, move to the bottom of the window with newlines, and print out "Running..."
* Then actually run the test.
* After it finishes, go back to waiting for changes.

Fortunately, thanks to the work @JPMoresmau did turning ghcid into an API, this shouldn't be too hard. Patches welcome :)

**Comment by cschneid** [comment]
first cut of this in PR #30

**Comment by ndmitchell** [comment]
Based on the code in #30 I implemented the feature. Can you give it a try and let me know your thoughts?

**Comment by ndmitchell** [comment]
Notes from @cschneid in #30, now that I closed the pull request.

- [ ] Render test output nicer
- [ ] Interrupt (?) test output on file save
- [ ] Stream test output
- [ ] Interpret exit code perhaps? Fold a successful test run back into "All good"

My thoughts: We can render it in a different color/style, that seems reasonable. Interrupting would require new support in our API, not sure how feasible that is. Streaming test output seems more hassle than its worth unless we have interrupting (since otherwise long tests aren't really practical anyway). We don't have access to the status code, but if you can figure out a way, that would be neat.

**Comment by meiersi** [comment]
I am working on a development mode for my blaze-react GUI library (https://github.com/meiersi/blaze-react/tree/feat-dev-mode), which could make great use of an interruptible `--test` command. 

The development mode is based on a web-server that runs the application under development in GHCi and serves a generic proxy single-page application that talks back to the web-server to handle events and fetch the pre-rendered blaze-react DOM. The proxy application is built using GHCJS and my blaze-react bindings to React.js. The dev-mode server application is built such that it continuously persists the application state, and thereby achieves state persistence over reloads.

I'd like to use the interruptible `--test` command to recompile and restart the dev-mode server on every file-change. This should enable sub-second latency between code-change and updated view of the blaze-react application in the browser.

I haven't looked at the `ghcid` code wrt. difficulty of this feature. So, I'm asking you how hard it would be to implement this interruptible test command feature. What protocol between GHCid and the running program do you imagine would work best?

**Comment by ndmitchell** [comment]
The current test command is run in process in the ghci session that is used for everything else, so is not interruptible at all. There are two ways to make it interruptible:

* Have a separate process for doing the test. That will slow things down a lot, as it will have to reload every file off disk.
* Find a way that given a console process connected to ghci you can send an abort signal to it, for example ctrl-c, in a way that is handled properly by ghci. I don't know if that is possible, but that would be the ideal place to start.

I suspect if you can find a way to send a ctrl-c it will be pretty easy, and if you can't, it will be very difficult.

**Comment by meiersi-11ce** [comment]
Thanks a lot for the detailed explanation. I'll look into it once I get the time.

**Comment by maxigit** [comment]
I have been using ghcid and hspec successfully with the following command line

    ghci -c"cabal repl hspec" -T":main --color -f failed-examples"

(My test suite is called `hspec`). Of course, if the tests are long, that could be a problem. However,
it is possible to tell `hspec` to fail at the first failure, by adding `--fail-fast` to the previous command.

**Comment by ndmitchell** [comment]
Looks like https://github.com/reiddraper/ordeal/blob/master/src/Ordeal.hs from @reiddraper might have the code we need to steal to send Ctrl-C to the prompt.

**Comment by ndmitchell** [comment]
The relevant code looks like:

```
signalProcessHandle :: ProcessHandle -> Signal -> IO ()
signalProcessHandle pHandle signal = do
    Just pid <- getPid pHandle
    let pId = CPid (fromIntegral pid)
    signalProcess signal pId
```

So just need to turn that into an API for `Language.Haskell.Ghcid`, probably `sendInterrupt`? And see if it's possible to make it work on Windows too, or if this has to be Linux-only to start with. Actually using it from within the ghcid executable should be pretty easy.

**Comment by reiddraper** [comment]
Awesome! I would love to be able to simply deprecate @reiddraper/ordeal in favor of ghcid. Right now I'm using both at the same time.

**Comment by reiddraper** [comment]
I wonder if restarting a long-running process (like a web-server) with ghcid should be treated differently than interrupting a test when the code changes? I'm not seeing any particular reason, but figured I'd ask.

**Comment by ndmitchell** [comment]
I'm not sure tests are particularly short - the Shake ones are 8+ minutes, so I think you have to assume tests take arbitrarily long and then they end up being exactly like a web server. If we had this I'd always run the test suite in the background, and never expect it to complete before restarting.

**Comment by reiddraper** [comment]
That seems reasonable to me.

**Comment by reiddraper** [comment]
@ndmitchell I'm happy to take a shot at this, not sure if you had started or not yet.

**Comment by ndmitchell** [comment]
I have not started, so go for it!

**Comment by luigy** [comment]
Hello I started things rolling for interruptible test command on #51 :)

**Comment by ndmitchell** [comment]
I've now completed the interruptible test command, working from @luigy's original patch. Main improvements are:

* Now you get streaming test output as its running.
* Lots of multithread issues have been addressed, we have a solid story for what the invariants are.
* I use a different method for killing off old ghci processes, meaning we don't need custom interrupt handlers, but can just use async exceptions.
* If interrupt doesn't work, I kill the ghci process and restart it - might be necessary for things with poor Ctrl-C handling.

Trying it in practice seems to work remarkably well.

I intend to release a new version of Ghcid incorporating these changes in the next few days, so if anyone wants to try in advance, please do so.

**Comment by simonmichael** [comment]
:+1:

**Comment by meiersi** [comment]
Awesome! I'm working on GUI stuff again, which prompted me originally to
look into that. I'll give your new code a go tomorrow.

Simon Michael <notifications@github.com> schrieb am Mo., 4. Apr. 2016 9:16
PM:

**Comment by meiersi-11ce** [comment]
Just tested it, and it works flawlessly! Great job guys!

I'll have to create a video on how super smooth HTML GUI development with Haskell can be :rocket:

**Comment by ndmitchell** [comment]
Thanks for the feedback. I've now released 0.6.1 with these changes in. Do share once you have the videos.

**Comment by luigy** [comment]
> Just tested it, and it works flawlessly! Great job guys!
>
>I'll have to create a video on how super smooth HTML GUI development with Haskell can be :rocket:

@meiersi-11ce I'm also very interested in this :)
keep us posted

**Comment by meiersi** [comment]
Yeah....I'm a bit underwater currently and on holidays next week. So you'll
have to be patient ;)

Luigy Leon <notifications@github.com> schrieb am Mi., 20. Apr. 2016 3:34 AM:

**Comment by rightfold** [comment]
Is it possible to only type check the tests, without running them?
