### ISSUE TITLE
Output file feature

### ISSUE THREAD

**Issue by mhitza** [ndmitchell/ghcid#31]
I would like an optional flag like `--output-file somefile` which would be written each time ghcid recompiles the program and would have the same information as the one displayed by ghcid. That way I could watch that file and invoke other utilities on successful compilation.

**Comment by ndmitchell** [comment]
Seems thoroughly reasonable. A few questions:

* ghcid deliberately truncates the file to N lines high, typically the size of the output window. Do you want that? I'd have thought you wanted the whole thing in untruncated glory, so you can truncate it differently as makes sense for the tool.
* You say "on successful compilation" - I guess you also want it written on erroneous compilations too?

**Comment by mhitza** [comment]
Personally I'm only interested on success "All good", so I would be ok with something as simple as 0 or 1 written into that file. But I guess, why be restrictive with the format?

I think it would make sense to dump the untruncated output into the file, some fellow vim user might load that file and `set autoread` on it instead of toggling between terminal tabs/splits/etc. I personally just want to write a Tcl script that sends ghci a `:r` when the file has been recompiled successfully.

**Comment by ndmitchell** [comment]
Added. Please let me know if it doesn't work as you had hoped. Only in the git version for now, but I'm hoping to make a release in the next week or so.

**Comment by mhitza** [comment]
Thanks, it works great.
