### ISSUE TITLE
Multiline errors/warnings

### ISSUE THREAD

**Issue by mustafahafidi** [ndmitchell/ghcid#318]
Hello all,
Thank you for this tool.
Is there a way to view multiline errors/warnings? currently `ghcid` reports only a single line out of each error/warning in ghci.

Thanks

**Comment by ndmitchell** [comment]
It reports multiline warnings for me just fine. Can you provide a screenshot/example of the problem? Is it possible your terminal size isn't being detected, in which case `--width=80` might help.

**Comment by mustafahafidi** [comment]
I was thinking the same, however that didn't solve the problem:
![Screenshot from 2020-05-28 11-04-02](https://user-images.githubusercontent.com/7404972/83121938-3cfd5380-a0d3-11ea-9296-2557507e506e.png)
Left is ghcid and right is ghci, as you can see ghcid is missing `Testnewline`

Running ghcid with `--verbose` :
```haskell
%MESSAGES: ...... loadMessage = ["/home/mustafa/coding/qc-to-lh/src/Test2.hs:(51,6)-(55,2): error:","    [qc-to-lh] error: Test"]}]
.....
/home/mustafa/coding/qc-to-lh/src/Test2.hs:(51,6)-(55,2): error:
    [qc-to-lh] error: Test
```
 `Testnewline` is not there. Is this verbose mode shows exactly what ghcid has been able to parse?

**Comment by mustafahafidi** [comment]
I throw the error with something like this
```haskell
failWith "Test\nTestnewline"
```

**Comment by ndmitchell** [comment]
Is this from a type checking plugin? Or a preprocessor? These don't appear to be normal GHC error messages. Note that Ghcid parses error messages in the style/format of GHC, and for those, there is the error message remains indented below the location. If you are generating your own messages, I suggest following the same style - e.g. `failWith "Test\n    Testnewline"`.

**Comment by mustafahafidi** [comment]
I see, it indeed works with the indentation. 
I have some preformatted messages from other tooling to report to the user. The idea is to keep the errors as they are with no added spacing.
But thank you for your help
