### ISSUE TITLE
Backpack mixins works except for module hiding

### ISSUE THREAD

**Issue by habibalamin** [ndmitchell/ghcid#327]
Hi,

I have a Cabal file with a `mixins` field set to:

```
  mixins:              base hiding (Prelude)
                     , protolude (Protolude as Prelude)
```

If I run `ghcid` like so:

```
cabal v2-exec ghcid -- -c 'cabal v2-repl'
```

or

```
cabal v2-exec ghcid
```

it results in an error message like this:

```
src/lib/ASDR.hs:1:8: error:
    Ambiguous module name ‘Prelude’:
      it is bound as Protolude by a package flag
      it is bound as base-4.14.0.0:Prelude by package base-4.14.0.0
  |
1 | module ASDR where
  |        ^^^^
```

This is a new project, so I'm not using the modules yet, just importing them, so I can remove the `mixins` field and observe that everything works as expected. I can also keep the `mixins` field and just run `cabal v2-repl` and again, everything works as expected.

Changing `base hiding (Prelude)` to `base (Prelude as SomeRandomOtherModuleName)` doesn't help either; I get the same exact error message, which is weird, because it suggests it's picking up the Protolude -> Prelude mapping, but not the Prelude -> SomeRandomOtherModuleName mapping (or maybe it's both retaining the old names _and_ picking up the new names?).

**Comment by habibalamin** [comment]
Hmm, [this](https://github.com/haskell/cabal/issues/5963) looks suspiciously relevant.

**Comment by ndmitchell** [comment]
Does `cabal v2-repl` on its own work? Ghcid roughly runs the repl, so if the underlying repl doesn't work, Ghcid won't. If you can get a working repl, then is the point to try and turn it into a Ghcid session. Personally, I've no idea about mixins.

**Comment by habibalamin** [comment]
Yes, it does. I even copied and pasted the default `cabal repl` command that `ghcid` prints out that it's running and that works, too. I spent ages looking at the `ghcid` codebase, because GHCi seems to do the right thing here, but couldn't find anything.

**Comment by ndmitchell** [comment]
I'm confused. You are saying `cabal v2-repl` works on its own to get you into a repl? If so, `ghcid -c "cabal v2-repl"` should work as well. I note the two things you've listed don't include that, so maybe that's the issue?

**Comment by ndmitchell** [comment]
There's the separate issue of whether ghcid defaults to the right thing - which is worth addressing - but I suggest we figure out how to get it working manually first, and then see about updating the defaults.

**Comment by habibalamin** [comment]
Yes, `cabal v2-repl` works and `cabal v2-exec ghcid -- -c 'cabal v2-repl'` doesn't (let alone something like `cabal v2-exec ghcid -- -c 'cabal v2-repl --repl-options=-fno-code'`). I'm as confused as you are.

**Comment by ndmitchell** [comment]
Yes, the cabal v2-exec sets up things such that cabal v2-repl doesn't work. I imagine `cabal v2-exec -- cabal v2-repl` would also fail for you.

**Comment by habibalamin** [comment]
Yep, sure enough that breaks in the same way.

Not sure if I should leave this issue open (with a new title and edited first comment). It still seems like buggy, or at least surprising, behaviour to me. I'm so used to prepending `$ISOLATION_TOOL exec $ISOLATED_EXECUTABLE -- "$@"` to make sure I always run the right version.

Maybe that was the wrong thing in this case, anyway, since I didn't put `ghcid` in the Cabal file. I guess I just ran it to make sure `ghcid` picked up my project, but I guess since it runs `cabal v2-repl` itself, it's already doing that.

**Comment by ndmitchell** [comment]
Maybe open it upstream on the Cabal github tracker? Since it seems like it's their issue underneath.

**Comment by habibalamin** [comment]
I'm gonna close this, and defer the decision of whether to open a new issue linked to this one to you. I've spent too long on this, even tried to hack up a FIFO-based solution, but ran into this issue any time I tried to run a function when running with `--repl-options=-fno-code`:

```
ghc: ^^ Could not load '_applescriptzmdictionaryzmreaderzm0zi1zminplacezmlibasdr_ASDR_asdr_closure', dependency unresolved. See top entry above.


ByteCodeLink.lookupCE
During interactive linking, GHCi couldn't find the following symbol:
  applescriptzmdictionaryzmreaderzm0zi1zminplacezmlibasdr_ASDR_asdr_closure
This may be due to you not asking GHCi to load extra object files,
archives or DLLs needed by your current session.  Restart GHCi, specifying
the missing library using the -L/path/to/object/dir and -lmissinglibname
flags, or simply by naming the relevant files on the GHCi command line.
Alternatively, this link failure might indicate a bug in GHCi.
If you suspect the latter, please report this as a GHC bug:
  https://www.haskell.org/ghc/reportabug
```

**Comment by ndmitchell** [comment]
If you have `-fno-code` then you can't run functions - those things are incompatible. `-fno-code` makes things go faster, but if you want to run too, you have to not pass it.

**Comment by habibalamin** [comment]
Ah, I see now that `ghcid` skips that option if I pass a `-T` argument. That makes sense.
