### ISSUE TITLE
ghcid --restart=dir closes when an error occurs

### ISSUE THREAD

**Issue by qwbarch** [ndmitchell/ghcid#364]
To run my tests automatically, I run the following:
```
ghcid --command "cabal repl test/Main.hs" --test "main" --restart my-project.cabal -W
```

The ``restart`` parameter is specifically to watch my cabal file in case I add dependencies.  
If there's any errors when I edit the cabal file, such as a missing comma, ghcid will halt and I'll have to start it again.  
How can I avoid this, and have ghcid attempt to restart again on any source changes?

**Comment by ndmitchell** [comment]
What does ghcid say when it halts?

**Comment by qwbarch** [comment]
Sorry for not including an error message. I somehow don't run into that issue anymore, sorry for the false alarm
