### ISSUE TITLE
fsnotify 0.4.0 release breaks building ghcid

### ISSUE THREAD

**Issue by codygman** [ndmitchell/ghcid#365]
It needs bounds but currently has none:

https://github.com/ndmitchell/ghcid/blob/abbb157ac9d06fdfba537f97ab96e197b3bb36cb/ghcid.cabal#L58

Reason for break from [fsnotify changelog](https://hackage.haskell.org/package/fsnotify-0.4.0.0/changelog):

> WatchConfig constructor is no longer exposed. Instead use defaultConfig {...} with the accessors. 

Error message:

```
src/Wait.hs:32:52: error: Not in scope: ‘confDebounce’
   |
32 | withWaiterNotify f = withManagerConf defaultConfig{confDebounce=NoDebounce} $ \manager -> do
   |                                                    ^^^^^^^^^^^^
Error: cabal: Failed to build exe:ghcid from ghcid-0.8.7. See the build log
above for details.
```

**Comment by ndmitchell** [comment]
Thanks - fixed in v0.8.8 and I added an upper bound in 0.8.7 as a Hackage edit
