### ISSUE TITLE
Windows 11 flags ghcid.exe as having trojan when built with stack

### ISSUE THREAD

**Issue by ThinkWiselyMatt** [ndmitchell/ghcid#387]
![image](https://github.com/ndmitchell/ghcid/assets/154620244/307f5dfc-60f1-47e5-84e5-d83a22969d2b)

Virus Total also reports when uploading the exe 

![image](https://github.com/ndmitchell/ghcid/assets/154620244/6a3410d4-8dfc-4e5f-b6b0-9ffa78164554)

Followed this guide for windows setup of Haskell : https://travishorn.com/haskell-development-on-windows

After
`stack install ghcid`
built the exe 

ran command 
`ghcid --command=stack ghci --test=main`

after running the tests on package the ghcid.exe was flagged and quarantined

Probably a false positive? 
I expect ghcid.exe does windows system calls to do the hot reloading that might look suspicious to the windows defender program

**Comment by ThinkWiselyMatt** [comment]
Microsoft confirmed false positive

**Comment by ndmitchell** [comment]
Yeah, unfortunately Haskell binaries generally aren't that well represented in the world, so virus scanners semi regularly tag them :(
