### ISSUE TITLE
Configurable number of lines for error messages?

### ISSUE THREAD

**Issue by afcowie** [ndmitchell/ghcid#42]
It would seem that **ghcid** is truncating error messages to 3 (?) lines. That's somewhat counter to what I was used to. I can imagine why you did it (sometimes you want to see all the errors, not just the first one) but I find myself having to ^C, run `stack build` manually to see the full error, then back to `ghcid`.

Am I missing something?

AfC

**Comment by ndmitchell** [comment]
If there are lots of errors, and only a few lines to display them, it truncates the first one to 3 lines, and the rest to 2 lines.  My workflow tends to be to resize the window if I really need more, but again, that's not great. https://github.com/ndmitchell/ghcid/blob/master/src/Ghcid.hs#L217 is the code that does this. Thoughts on what the algorithm should be? Or should there be a key to toggle, as per #10?

**Comment by afcowie** [comment]
So if you're talking about "key to toggle" that implies a) changing focus to that window and b) making it a more interactive environment. Which is a very cool idea indeed, though I would point out that right now the attraction of **ghcid** is, to some extent, that I don't have to leave the editor. That said, navigating through the errors with, say, the arrow keys, would be something to think about. If that's the case, I would encourage you to look at the UX of `perf top` on a Linux box. It's surprisingly solid.

Meanwhile as for the height to show, I seriously wonder if there's any value to showing more than one at a time (I wish **ghc** had an equivalent to **gcc**'s `-Wfatal-errors`), but I suppose `--max-errors=n` option would do the trick (default 1 :)). If not, then maybe just divide available height by number of errors (but still capping it at say a minimum of 5 lines per error).

2¢

AfC

**Comment by ndmitchell** [comment]
Agreed, I'd rather the interactive features be an added bonus, rather than a necessity. I haven't tried `perf top`, but then I'm not a Linux user.

So I already follow your idea of dividing available height by errors, but use a minimum of 3 lines for the first error and 2 for subsequent errors. I'll try increasing the first error height to 5 and see how that feels locally. I'm not against a max-errors, or a minimum-first-height option (where infinity gives you roughly the same thing), but one less flag for users to have to fight is always preferable.

**Comment by afcowie** [comment]
I tried hacking it to a max 5 lines per error for all of them and it seemed to feel ok. {shrug}

**Comment by ndmitchell** [comment]
I think the first error having special treatment seems like a good idea - it's the one you should be focusing on - other than that its nice to know where other errors are as they are sometimes fallout, or sometimes GHC picks the wrong line.

Out of curiosity, how many lines (roughly) do you typically have for ghcid? I am usually on about 7.

**Comment by ndmitchell** [comment]
OK, first error is 5 lines high. Let's hope that fixes it, but please reopen if it doesn't seem to do what you are after.

**Comment by afcowie** [comment]
@ndmitchell How many lines? Full terminal, so 80x24 standard if stand alone or half a screen, which is 72x37 on this monitor with this font size today.

(half a screen for editor, other half for terminal with ghcid in it.... in no small part because I want to see the whole error message, not the single line that ghc-mod and friends provide. Quite tedious to have to abort ghcid and run the build manually just to see the error)

I'll keep experimenting with it!

AfC

**Comment by ndmitchell** [comment]
Ok, I use 7, so I've inadvertently optimised for that. I'll try and figure out a more sensible default.

**Comment by feuerbach** [comment]
I think that the first error should be shown entirely. What's the point of seeing many errors at once if you can't fix any of them? You're assuming that the first n lines of the error message are somehow more important than the rest; I don't see any ground for this.

**Comment by ndmitchell** [comment]
@feuerbach, the first 2 lines have the type of error and the file/line so are definitely most important. I am gradually coming round to showing the first error in full, since if you don't then you really want an option to show it in full, and better default to no options if you can.

**Comment by feuerbach** [comment]
@ndmitchell you are thinking about a specific kind of errors. For instance, I had an ambiguous identifier error recently, and the second conflicting import wouldn't come until the line 6 or 7.

But even in case of type errors, I find the information contained in the message very useful.

**Comment by jtdaugherty** [comment]
For what it's worth, I am going to release a new terminal UI programming library (probably in the next few weeks) that would be a great fit for putting an interactive UI on top of `ghcid`.  I will probably mess around with such a thing myself.  The library is https://github.com/jtdaugherty/brick.

**Comment by ndmitchell** [comment]
@jtdaugherty, does the library works on Windows? From what I can see, the `vty` dependency doesn't?

**Comment by ndmitchell** [comment]
The basic algorithm at the heart of the bug is given a list of multiline items (errors followed by warnings), and a height, how do you pack them. The old algorithm was:

    take (max 5 $ height - (length msgs * 2)) (head msgs) ++ concatMap (take 2) (tail msgs)

The new algorithm is:

   take height $ concat msgs

This guarantees the first message will be shown in full, as will any subsequent messages, until it runs out of space. It means you get more information about fewer messages. Does that seem to be what people are after?

**Comment by feuerbach** [comment]
Looks good to me.

**Comment by jtdaugherty** [comment]
@ndmitchell - good question! `vty` claims to support Cygwin only. I haven't made any special effort to support Windows in my package, but I don't test on Windows, either.

**Comment by afcowie** [comment]
@ndmitchell I think that'll be fine. I know you went to a lot of trouble to compactly show messages, but honestly if people want all the errors, then they can use ghc-mod et al to give them red squigglies in their editor at all the error sites with then incomprehensible one line messages.

**Comment by ndmitchell** [comment]
This seems to work nicely for me, so considering it fixed.
