### ISSUE TITLE
Oneshot mode for scripting

### ISSUE THREAD

**Issue by cheecheeo** [ndmitchell/ghcid#47]
`ghcid` is the quickest way for me to test my code, faster than `cabal test` and `stack test`. I'd like to use `ghcid` in a pre-commit hook but `ghcid` doesn't support a oneshot mode as far as I understand it. 

Simply using `echo test | cabal repl` doesn't work for me because `cabal repl`'s return codes aren't meaningful.

**Comment by ndmitchell** [comment]
Isn't `runhaskell` essentially a one-shot version of `ghcid` already? Could `stack` get a `--runhaskell` argument to `stack test`? I'm not necessarily against this, but it seems a bit weird for `ghci` to take a continuous program, turn it into a daemon, then have a flag to turn it back to one-shot.

**Comment by ndmitchell** [comment]
I'm going to close this for now, but do reraise if testing shows `ghcid` to be faster than `runhaskell`, which is probably the best solution to use.

**Comment by cheecheeo** [comment]
Fair enough, thanks for the pointer.
