### ISSUE TITLE
identifier not shown because of extra line break in "variable not in scope" 

### ISSUE THREAD

**Issue by jwaldmann** [ndmitchell/ghcid#48]
when ghc(i) outputs an error message

```
src/Matchbox/Automaton/Plain.hs:180:27: error:
    • Variable not in scope:
        domainL
          :: R.Rel p q (Path q1)
             -> t0 containers-0.5.7.1:Data.IntSet.Base.Key
```
then ghcid does not show the name:
```
src/Matchbox/Automaton/Plain.hs:180:27: error:
    • Variable not in scope:
src/Matchbox/Relation.hs:103:1: warning:
```
I guess this is because of the extra line break, because it works if the error message is like this
```
src/Matchbox/Automaton/Plain.hs:49:31: error:
    • Variable not in scope: auto :: Aut Q c0 (Path Q)
```
then ghcid handles this fine.

I think haskell-mod has the same problem. The extra line break could be flagged as a bug (misfeature) in ghc?

**Comment by ndmitchell** [comment]
Can you upgrade to the HEAD version in the git repo? I think this may be something that I've since fixed, by ensuring the first error always gets more lines to display.

**Comment by jwaldmann** [comment]
Ah, "first error" is the key here. 

I was not looking at a first error, because of https://ghc.haskell.org/trac/ghc/ticket/11541 

You are not actually parsing the error messages except for their line structure?

**Comment by ndmitchell** [comment]
I do not parse the GHC errors fully - I split them up into separate errors, and then truncate errors after the first one. If you make the ghcid window larger it will take up more space, and then subsequent errors will display with more lines. I don't see any real way around this if you want to see more than the first error.

**Comment by jwaldmann** [comment]
> ... no way around

if you want to keep original line breaks, yes. I was suggesting to remove some.

But since the ghc issue is fixed (in HEAD), a nice display of the first error should be enough.

**Comment by ndmitchell** [comment]
I'm not averse to displaying certain errors more compactly - for example I drop lines beginning with `To import instances alone, use: import` since they don't have any meaningful information.

Perhaps the rule could be if the message is N lines long, and I'm displaying fewer lines than that, on the final line I drop all newlines and just shift extra stuff along? Worst case is you'll get confused, but normally you'll get more information. In your case that would give:

    src/Matchbox/Automaton/Plain.hs:180:27: error:
        • Variable not in scope: domainL :: R.Rel p q (Path q1) -> t0 containers-0

Which is indeed significantly more useful.

**Comment by ndmitchell** [comment]
In HEAD all errors and warnings get displayed in full without being truncated after 2 lines, so this is no longer a problem.
