### ISSUE TITLE
Custom command for reloading

### ISSUE THREAD

**Issue by LukaHorvat** [ndmitchell/ghcid#49]
Due to some circumstance, my project doesn't reload properly with `:reload`. I need to write `:load app/Main.hs` for it to work properly. It would be nice if we could provide a custom reload command.

**Comment by ndmitchell** [comment]
I'm not against it, but I'd like to understand why it's useful first. Why doesn't `:reload` work for your project?

**Comment by LukaHorvat** [comment]
To be honest, I have no idea. It's basically an empty yesod template. I think it's something to do with TH not reloading properly.

**Comment by ndmitchell** [comment]
Which version of GHC? I think it would be worth getting to the bottom of, as it probably represents either a GHC bug or a Yesod bug, and is probably worth fixing at source if possible.

**Comment by LukaHorvat** [comment]
GHC 7.10.3
Latest stack, latest LTS snapshot.
I'd be glad to get to the bottom of this. I'm guessing this isn't the appropriate repository for that.

**Comment by ndmitchell** [comment]
None of that seems particularly unusual. Given your project is based on the Yesod scaffolding project, I suggest raising it with the Yesod developers in the first instance. If you can, try and see if it still happens with exactly the Yesod scaffold project, since then it's a bug without involving any code you changed.

**Comment by ndmitchell** [comment]
It sounds like the bug lies elsewhere, but you can actually already work around it in `ghcid`. All `ghcid` does is fire `:reload`, and you can change to a different `:reload` with a `.ghci` file containing:

    :def reload \_ -> return ":load app/Main.hs"
