### ISSUE TITLE
Consider -fno-code

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/ghcid#50]
Loading Shake with `ghci -fno-code` is a big win - I load in 3.61s instead of 5.55s, and working set memory is 130Mb instead of 200Mb. The downside is that you can't actually execute code. In general most `.ghci` files won't execute code, but they potentially can. The test command if present will almost certainly execute code. Therefore I suggest we:

* Add `-fno-code` by default, unless:
  * Either: The user passes `--code` or some similar flag.
  * Or: the user passes a `--test` expression.

**Comment by reiddraper** [comment]
:+1:

**Comment by ndmitchell** [comment]
Thinking about it, if the `.ghci` file can counteract `-fno-code` then there's no need for a flag.

**Comment by ndmitchell** [comment]
Done!
