### ISSUE TITLE
rerun when cabal file changes (and also when `package.yaml` changes)

### ISSUE THREAD

**Issue by silky** [ndmitchell/ghcid#52]
suppose i change my cabal file (or similarly when my `package.yaml` changes, which will generate a new `cabal` file when stack runs); can `ghcid` rerun then? would this be a bad idea for any reason?

**Comment by ndmitchell** [comment]
ghcid already does that - if you use the default options and it select something like `cabal repl` as the command it sets  the cabal file to restart on. If you are passing a custom command, you can pass custom restart files with `--restart`. I just checked the code - in the case of package.yaml I had missed reloading if the cabal file changes, so I've now fixed that.

**Comment by silky** [comment]
thanks for pointing me at the `--restart` option; should've looked, i'm using that now :)
