### ISSUE TITLE
some way to pass in the cabal files extensions?

### ISSUE THREAD

**Issue by silky** [ndmitchell/ghcid#53]
i'm not entirely sure if this is the job of ghcid, but i'm using the `NoImplicitPrelude` extension, and thus my `ghcid` command starts off like ...:

````
ghcid --command="stack ghci --ghci-options -XNoImplicitPrelude ...
````

it'll get more crazy as i care about more extensions. but shouldn't we just be able to load with the extensions that are found in the cabal file? am i missing some reason that this isn't a good idea?

**Comment by silky** [comment]
actually this isn't a problem with ghcid; this happens with `stack ghci` itself; my bad.

**Comment by ndmitchell** [comment]
If `stack ghci` doesn't start with all the appropriate extensions in your .cabal file then that's a stack bug - and I would encourage you to report it. It's probably relatively easy to fix, and the stack devs are quite responsive.

**Comment by mgsloan** [comment]
`stack ghci` does load the extensions specified in the cabal file.  Perhaps you have extensions specified in benchmark or test stanzas?  These will not be loaded unless test / bench targets are specified.

**Comment by silky** [comment]
yeah, sorry, it's just when i tried `stack exec -- ghci app/Main.hs` i noticed this; but that's just me not understanding what ghci does when i pass it arguments. i don't think it should be trying to load the extensions there, so it doesn't.

my mistake; sorry for the noise :)
