### ISSUE TITLE
help improvement suggestion

### ISSUE THREAD

**Issue by rvion** [ndmitchell/ghcid#58]
minor help text improvement suggestion:

current:
```shell
     --reload=FILE      Reload if any of these files change (defaults to
                        none)
     --restart=FILE     Restart the command if any of these files change
                        (defaults to .ghci or .cabal)
```

suggestion:
  - replace `FILE` by `PATH`
  - replace `(defaults to .ghci or .cabal)` by `(defaults to .ghci and .cabal)`
  - replace `any of these files` (that let one think that we can pass several files space separated using shell expansion) by something like `given file or folder files` or `{ given file | files in given folder }` (no strong opinion on specific wording, but current one seems to imply I can pass --reload="foo foro/bar baz" which doesn't work
 
```shell
     --reload=PATH      Reload when { given file | files in given folder } change (defaults to
                        none)
     --restart=PATH     Restart the command when given file or folder files change
                        (defaults to .ghci and .cabal)
```

**Comment by ndmitchell** [comment]
I'd rather avoid something like `{ ... | ...}` - it seems to imply a deeper semantics than is really there. How about:

    --reload=PATH    Reload when the given file or directory contents change (defaults to none).
    --restart=PATH    Reload when the given file or directory contents change (defaults to .ghci and any .cabal file)

**Comment by rvion** [comment]
I agree. English reads better

(I used both `{|}` and plain english above just to see how it looks like / raise possible alternatives)

**Comment by ndmitchell** [comment]
I went with:

     --reload=PATH      Reload when the given file or directory contents
                        change (defaults to none)
     --restart=PATH     Restart the command when the given file or directory
                        contents change (defaults to .ghci and any .cabal file)
