### ISSUE TITLE
Stack-based project not recognized

### ISSUE THREAD

**Issue by k-bx** [ndmitchell/ghcid#62]
I have a root project dir with `stack.yaml`, and then multiple sub-directories, which don't have `stack.yaml` in them, but they all are built with stack. When you run "stack build" inside any of those dirs (with cabal projects inside), stack will go upper, find stack.yaml and use that.

ghcid, unfortunately, doesn't behave the same. It just doesn't see "stack.yaml" and tries cabal instead (obviously failing).

**Comment by ndmitchell** [comment]
Hmm. Since `ghcid` is designed to work with both `stack` and `cabal`, do you have any suggestions for how it could reasonably decide? Is going up one level sufficient? Are there any places where people will want to use Cabal, but inadvertantly have a stack one level up?

**Comment by k-bx** [comment]
Good question. I think ghc-mod had similar question. I think what they do is – they look for `dist` directory (or `.cabal-sandbox` or similar, don't remember already what's the name of cabal build artifacts in different settings) and decide it's cabal project, otherwise they try to find `stack.yaml`, otherwise fallback to just `ghc`. Something similar, possibly with a limit of a level which you go up, would probably be best to implement.

**Comment by ndmitchell** [comment]
That sounds reasonable - if anyone can point me at the exact logic they use it might be best to share.

**Comment by k-bx** [comment]
@DanielG does ghc-mod have a page or source file location which could easily describe the mechanism of determining if a project is a cabal, stack or pure-ghc-based? I only found [wiki page](https://github.com/DanielG/ghc-mod/wiki) which says:

> Make sure the dist/setup-config file doesn't exist in your project directory (the directory also containing your *.cabal file). When this file exists ghc-mod assumes you want to use cabal-install instead of Stack.

Help would be appreciated. Thank you!

**Comment by ndmitchell** [comment]
Here's the current logic in ghcid: https://github.com/ndmitchell/ghcid/blob/master/src/Ghcid.hs#L86

**Comment by DanielG** [comment]
Sure thing, the logic is here: https://github.com/DanielG/ghc-mod/blob/master/Language/Haskell/GhcMod/Cradle.hs#L43 just `msum`s a bunch of MaybeT actions together effectively picking the first one that doesn't `mzero`. The bail out in the stack + cabal `dist` case is here: https://github.com/DanielG/ghc-mod/blob/master/Language/Haskell/GhcMod/Cradle.hs#L101

I wouldn't recommend this exact logic though this has caused quite a lot of trouble for users upgrading from cabal. Just an additional check if a) `stack` is actually installed and b) if just `ghc` even exists in the global PATH might give additional clues though.

See also: https://github.com/DanielG/ghc-mod/issues/776 though that's just the most recent issues of many mentioning this problem.

**Comment by ndmitchell** [comment]
Sounds like we need to kill either Cabal or Stack to get our sanity back... Thanks for the info, I'll see what I get to.

**Comment by ndmitchell** [comment]
I've just tweaked my logic to also look for `../stack.yaml`. I think in comparison to @DanielG I'm defaulting to Stack if the user looks like they are using Stack, on the grounds that's less common. But whatever happens is a mess and there's no real way for tool authors to handle it properly :disappointed:.
