### ISSUE TITLE
Turn test errors into failing titlebar/icon

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/ghcid#63]
Ghcid should detect if a test fails, and if so change the icon and title to indicate as such.

For Shake tests, a failure is if the final line of stderr in a test is `*** Exception:` not followed by ExitSuccess. I should also look at what the Ghcid test does, which is driven by HUnit, and thus a "Haskell standard" as far as it goes.

**Comment by luigy** [comment]
Hey I've been meaning to bring ghcid's osx support up to par with windows (native notifications and maybe also the titlebar icon(will have to look more into this second one))

What is in Terminal.hs pretty much :)

I wouldn't mind maintaining these bits

**Comment by mgsloan** [comment]
Keep in mind some folks don't have titlebar / icon, like when using xmonad.  Sounds good tho

**Comment by ndmitchell** [comment]
@mgsloan, these features are added extras only, although very useful in my experience.

@luigy, patches most welcome!

**Comment by ndmitchell** [comment]
Now done. Seems everything raises a bad exception when failing, so I'm able to just watch for that.
