### ISSUE TITLE
use ghcid as a general file watcher/command runner?

### ISSUE THREAD

**Issue by jwaldmann** [ndmitchell/ghcid#65]
Could ghcid be extended for the use case of running a command whenever a specific file (or one of a set of files) changes? For the case that the command *does* exit each time (say, latex, make, or lilypond).

I naively tried `ghcid -c 'lilypond foo.ly' --restart=foo.ly` - this runs just once, then stops with "command exited unexpectedly". 

That's probably outside the intended application domain of ghcid, and perhaps there's some emacs magic that would achieve the same, but I like the ghcid approach to things.

**Comment by mitchellwrosen** [comment]
Would https://github.com/steeloverseer/steeloverseer suffice?

`sos -c 'lilypond foo.ly' -p 'foo.ly'`

Or, to trigger on any `.ly` file in the current directory tree:

`sos -c 'lilypond \0' -p '.*.ly'`

**Comment by ndmitchell** [comment]
I'm not adverse to simple and light tweaks that make it more useful outside the intended domain, but nothing too significant. I would imagine `ghcid --test ':!lilypond foo.ly' --restart=foo.ly` might work, and if it didn't it could be modified to make it start working.

That said, maybe a link to `sos` in the README might be better - they are different problems, and sos seems to have a lot of nice features that anyone who starts to push ghcid down this route will quite quickly want.

**Comment by jwaldmann** [comment]
Thanks. I did not know sos. It looks fine for the job.

**Comment by ndmitchell** [comment]
I'll leave this ticket to link to sos - seems like a sensible companion project to point people at.

**Comment by ndmitchell** [comment]
Link added.
