### ISSUE TITLE
readme and quit

### ISSUE THREAD

**Issue by stevezhee** [ndmitchell/ghcid#74]
A couple of updates to the readme... when it says you can't run arbitrary commands perhaps you should note that you can run an arbitrary haskell function via --test (awesome feature BTW!)

The link to Steel Overseer doesn't work.

Is it possible to show the ghci output after running the --test function?

Is there a clean way to exit?  It seems particularly difficult to kill it (not sure if this is just a windows problem)

**Comment by ndmitchell** [comment]
Good point about the readme, I'll clean that up.

You do get to see the ghci output after running `--test` - or at least you should with the latest version. Can you try a dummy test case like `--test=1+2`? Note the test output will be at the bottom of the screen.

I develop ghcid almost exclusively on Windows and Ctrl-C in the window always works perfectly for me - I have some logic to try and super robust. Does that not work for you?

**Comment by stevezhee** [comment]
This is version 0.6.4 running in a cygwin bash window on windows.
My command is: ghcid --command="stack ghci" --test="main" -W -t -v
I don't see anything from the dummy test case either.
If I Ctrl-C in the window it actually locks it up.  Even when I use task manager to kill ghcid and ghc and try to close the window it takes awhile for the window to go away.  Actually if I just close the window that's the cleanest way I've found and it takes around 13 seconds.

**Comment by ndmitchell** [comment]
I'm going to guess cygwin is at least partly responsible here - running from a normal windows prompt works fine. Which cygwin terminal emulator are you using? I believe mintty is the default.

**Comment by ndmitchell** [comment]
Just trying it in my version of Cygwin I see that the test output doesn't show up, but that Ctrl C does reliably kill it. I also observe that the auto-height detection doesn't work.

**Comment by stevezhee** [comment]
Yes - it does seem to be a problem with mintty (my version is 1.1.3).  Everything works fine in a windows prompt as you said.  Thanks!

**Comment by ndmitchell** [comment]
I've just pushed a fix for flushing which means the test output now shows up immediately in Cygwin. I can't replicate the Ctrl-C issue though - it works flawlessly for me.

**Comment by stevezhee** [comment]
I think the Ctrl-C issue is a mintty problem.  A coworker is using a newer version of mintty and his works fine.

**Comment by ndmitchell** [comment]
I'm using mintty 1.1.2 and it works fine. However, if newer mintty works I'll consider that a mintty bug and not worry about it.

**Comment by ndmitchell** [comment]
Readme updated, and more flushing for Cygwin, so I think that's all the issues addressed - but let me know if I missed something. Thanks for all the comments.

**Comment by stevezhee** [comment]
Yes - with an updated mintty and the latest ghcid the issues are resolved.  Thanks!
