### ISSUE TITLE
Colored output

### ISSUE THREAD

**Issue by talw** [ndmitchell/ghcid#75]
It could be useful if ghcid had colored output.
Allows the eyes to parse those type check errors faster.

There is a solution for ghci, for example this script: https://github.com/rhysd/ghci-color.
However, this doesn't integrate readily with ghcid, at least not in a way I'm aware of.

Please excuse this issue if supporting such a feature is beyond the intended scope of ghcid, and perhaps the solution should be implemented externally. And if it is I'd appreciate a hint as to the form it should be implemented as.

**Comment by ndmitchell** [comment]
It already has "coloured" output, it just so happens those two colours are normal and bold (aka light gray and bright white on most terminals). What were you thinking should be in different colors?

The relevant code would probably want to go near or in https://github.com/ndmitchell/ghcid/blob/master/src/Ghcid.hs#L226.

**Comment by talw** [comment]
Oh of course, I did notice the bold parts, but I thought of something along the lines of:
https://wiki.haskell.org/wikiupload/a/ad/Coloured-error.png
But this depends on having the message parsed, or at least getting an AST output of something that parsed it.

**Comment by ndmitchell** [comment]
I find that pretty ugly - highlighting instance and of despite not being keywords in this context, plus the general colour scheme seems to "bright". If we can come up with something that makes it easier to get at the relevant part of the error quickly that does seem useful though. I suspect that was done with just a lexer, not a full AST, so shouldn't be too hard to replicate if we do want to go that route.

**Comment by talw** [comment]
You're right, I didn't refer to that exact coloring scheme, Just to the granularity level (not including marking non-keywords in different colors!)

Speaking of coloring scheme though, everyone has different backgrounds and color preferences, so I'm not so sure if there are sensible defaults we can use.
The approach you took with the bold was good in that regard, as it is neutral.

**Comment by ndmitchell** [comment]
The question I'd like to consider first is what additional information would it helpful to highlight?

* File location? Perhaps, but it's always on the first line without indents, so in a way that's already clear.
* Brackets? Useful when matching brackets, but I rarely find that's the cause of an error in ghci (because you only really get the brackets out of the AST error messages, by which time you know they are correct)
* Literals? Again, these are correct by the time you see them in errors such as above.

**Comment by talw** [comment]
The thing I thought would be helpful to highlight is basically type signatures.
Namely, the expected and actual type signatures, as they are the bread and butter when I'm fixing errors. I assume that's not just me.
I find it easier to mentally parse Either of List of Tuples etc. when parentheses, type constructors, type constructor arguments and type variables are all colored differently.

**Comment by ndmitchell** [comment]
With the palette available on the console we don't have that much scope for subtle colorings, or too many variants. But I do agree that a type signature is easier to grok when its got some syntax highlighting on it. One remaining concern is that in fact when diagnosing errors I tend to jump for the line/column, but mostly ignore the error message, especially if its longer than a few lexemes, which is the case coloring helps.

My guess is this is something I wouldn't want, but it seems entirely reasonable for a large number of people, so having a `--color` flag that colorises the output in some way seems sensible and desirable. Whether it becomes a default or not probably depends on how intrusive/helpful it is in practice. I welcome pull requests.

**Comment by talw** [comment]
I've found a good alternative that does not reinvent the wheel!
For vim users: use neovim! Run terminal in neovim, run ghcid, and mark the whole buffer as filetype haskell, so that it is syntax highlighted as if it was a Haskell file.
For emacs users: Apparently, they can use the same trick!

And you get the colors you use from your favorite editor, for free :)

**Comment by ndmitchell** [comment]
Neat idea! That really does solve all the issues with customisation and a weak palette of colors. I've added it to the FAQ, since it's useful and not immediately obvious.

**Comment by talw** [comment]
Great! I'm sure it'll help others who face this issue.
