### ISSUE TITLE
`-fno-code` means that warnings are not reported with ghc-8.0.1

### ISSUE THREAD

**Issue by lspitzner** [ndmitchell/ghcid#76]
I had `-Wall -Werror` and default ghcid invocation still did not return the warning-errors. Apparently -c defaults to `cabal repl --ghc-options=-fno-code`, which is neither documented nor beneficial in this case.

(one may wonder whether the behaviour of ghci -fno-code is correct, though.)

**Comment by ndmitchell** [comment]
Where did you have `-Wall -Werror`? There's typically very little need to given `-Werror` to `ghcid`, since it reports all warnings and errors persistently, so there's little chance of missing one, but it's not particularly harmful either.

The `-fno-code` probably makes your project take half the time to reload, and shouldn't have any effect on errors or warnings. It's almost universally a good thing to have for `ghcid`, which is why it's automatic.

The behaviour of `-c` is documented at https://github.com/ndmitchell/ghcid#using-it. It says:

> If you omit --command then it will default to stack ghci if you have the stack.yaml file and .stack-work directory, default to ghci if you have a .ghci file in the current directory, and otherwise default to cabal repl

So I guess the real question is how did you think `-Wall` was getting to `ghcid`? My guess is that whatever you did didn't have the effect you were hoping for, and the `-fno-code` is a red herring.

**Comment by lspitzner** [comment]
> Where did you have -Wall -Werror?

In my .cabal file.

I looked at the verbose output. `-Wall` is getting to the ghc invocation behind ghcid, because it is invoking, quote:

~~~~
Loading cabal repl --ghc-options=-fno-code ...
~~~~

And `cabal repl` respects the (configured) ghc-options from the .cabal file. The above line is the first line of output from a plain `ghcid -v`.

Also: Thanks for ghcid! working around this issue, i managed to integrate ghcid into my editor (sublime), providing fast feedback every time i press save. really useful!

**Comment by ndmitchell** [comment]
So are all the `-Wall` warnings coming back? Was it just the Loading message that was confusing?

Glad you've got it working. I also use Sublime, but haven't really got any editor integration, besides running ghcid nearby. If you have any tricks for ghcid integration other than a separate console window I'd love to hear them.

**Comment by lspitzner** [comment]
no, my workaround is adding `-c "cabal repl"`. Only then do i see warnings.

**Comment by lspitzner** [comment]
my sublime setup involves a custom sublime "build system" and a modified version of the "SublimeOnSaveBuild" plugin. I will describe/upload the details in the evening; busy right now.

**Comment by ndmitchell** [comment]
I just added `ghc-options: -Wall` to the library section of the shake project, which caused lots of warnings to appear. I then ran `ghcid`, which used `-fno-code` and it showed 384 warnings, compared to 0 normally. Which version of Cabal are you on? In my instance, the child process was spawned with:

```
"C:\ghc\minghc-7.10.2-i386\ghc-7.10.2\bin\ghc.exe" "--interactive" "-fbuilding-cabal-package" "-O0" "-outputdir" "dist\build" "-odir" "dist\build" "-hidir" "dist\build" "-stubdir" "dist\build" "-i" "-idist\build" "-isrc" "-idist\build\autogen" "-Idist\build\autogen" "-Idist\build" "-optP-include" "-optPdist\build\autogen\cabal_macros.h" "-this-package-key" "IorBoo24fwxI7yJJ71RfSk" "-hide-all-packages" "-package-db" "dist\package.conf.inplace" "-package-id" "base-4.8.1.0-4411f755eeebe72a83715ecebc424dd9" "-package-id" "binary-0.7.5.0-21bfb535c2e89240dc3af41aa36d9b4d" "-package-id" "bytestring-0.10.6.0-3a6a732ee0b8cb400ce04a0f0a3f15e6" "-package-id" "deepseq-1.4.1.1-10f84b191b92d4df5a1b62ef8443e7d6" "-package-id" "directory-1.2.2.0-67861052f6528c2b3ae07ef68f3c2799" "-package-id" "extra-1.4.10-9d2h4XoSoen1S5BPfy7889" "-package-id" "filepath-1.4.0.0-ae307811bafd730695e1b4e0d36c99da" "-package-id" "hashable-1.2.3.3-5df1f116b1107918ada93396c40c0fc5" "-package-id" "js-flot-0.8.3-b39df1fd9385718ee28d89b306e984ca" "-package-id" "js-jquery-3.0.0-GHzSD0MwJ7iCDGXOJtyZuo" "-package-id" "primitive-0.6-d6942db654eb32f8734d0ca14d78c0ba" "-package-id" "process-1.2.3.0-e80848e270871e1a525ad6051db8884a" "-package-id" "random-1.1-d7947242678fe66ea011f9af3def6123" "-package-id" "time-1.5.0.1-802c20236039b7ed50da988195abc16b" "-package-id" "transformers-0.4.2.0-92071d0128abe0876342c7281d6628ae" "-package-id" "unordered-containers-0.2.7.0-fb2498ccd7681d07a77d680f086cc3ce" "-package-id" "utf8-string-1.0.1-c7ff506192ad47b5c97ce5cb03ea9c89" "-XHaskell2010" "Development.Shake" "Development.Shake.Classes" "Development.Shake.Command" "Development.Shake.Config" "Development.Shake.FilePath" "Development.Shake.Forward" "Development.Shake.Rule" "Development.Shake.Util" "Development.Ninja.Env" "Development.Ninja.Lexer" "Development.Ninja.Parse" "Development.Ninja.Type" "Development.Shake.Internal.Args" "Development.Shake.Internal.ByteString" "Development.Shake.Internal.Core.Action" "Development.Shake.Internal.Core.Rules" "Development.Shake.Internal.Core.Run" "Development.Shake.Internal.CmdOption" "Development.Shake.Internal.Core.Database" "Development.Shake.Internal.Demo" "Development.Shake.Internal.Derived" "Development.Shake.Internal.Errors" "Development.Shake.Internal.FileInfo" "Development.Shake.Internal.FilePattern" "Development.Shake.Internal.Core.Monad" "Development.Shake.Internal.Core.Pool" "Development.Shake.Internal.Profile" "Development.Shake.Internal.Progress" "Development.Shake.Internal.Resource" "Development.Shake.Internal.Rules.Directory" "Development.Shake.Internal.Rules.File" "Development.Shake.Internal.Rules.Files" "Development.Shake.Internal.Rules.Oracle" "Development.Shake.Internal.Rules.OrderOnly" "Development.Shake.Internal.Rules.Rerun" "Development.Shake.Internal.Shake" "Development.Shake.Internal.Special" "Development.Shake.Internal.Core.Storage" "Development.Shake.Internal.Types" "Development.Shake.Internal.Value" "General.Bilist" "General.Binary" "General.Cleanup" "General.Concurrent" "General.Extra" "General.FileLock" "General.Ids" "General.Intern" "General.Process" "General.String" "General.Template" "General.Timing" "Paths_shake" "-Wall" "-fno-code"
```

Which seems reasonable - I see `-Wall -fno-code` at the end, where `Wall` gives all the warnings and `fno-code` gives faster reload.

**Comment by ndmitchell** [comment]
Oh, and your sublime setup sounds great - no rush on the details, but I would like to try it out - having double click to go to line number would be most helpful.

**Comment by lspitzner** [comment]
oh, maybe it is ghc that changed behaviour? i'll check that, one sec.

**Comment by lspitzner** [comment]
indeed. ok, with ghc-8.0.1, certain warnings are not reported when `-fno-code` is enabled, while with ghc-7.10.3, the same warnings are reported. Sorry for not considering this possibility earlier.

already tracked at https://ghc.haskell.org/trac/ghc/ticket/10600

**Comment by lspitzner** [comment]
@ndmitchell for my sublime setup, see https://gist.github.com/lspitzner/5ae6638554f9e7457dccb462cb415987

with that, you even can press f4 to get to error location :)

**Comment by lspitzner** [comment]
@ndmitchell oh i forgot to add the .hs to the SublimeOnSaveBuild. added to my fork now, or you can edit your local plugin settings.

**Comment by ndmitchell** [comment]
The GHC 8.0.1 thing is very annoying. I guess the only reasonable thing is to disable `-fno-code` until the GHC team fixes this.

**Comment by ndmitchell** [comment]
Hmm, which warnings are affected? Just incomplete patterns, or anything else?

**Comment by lspitzner** [comment]
i have only observed it for incomplete patterns, and would assume the ghc ticket would mention other warnings if affected. Have not investigated though.

**Comment by ndmitchell** [comment]
Hmm, if it's only incomplete patterns and only with one compiler version I might not worry as much.

**Comment by ndmitchell** [comment]
So the options are:

* Warn people in the README.
* Have a flag to disable the adding of `-fno-code`.

Any suggestions on what if anything I do from that list?

**Comment by lspitzner** [comment]
Let me put it this way: As a user, i found annoying that README / commandline --help did not mention that `-fno-code` was appended. Once i found out what was going on, adding `-c cabal repl` was quick. So my priorities would be:

1. Document that `-fno-code` is used.
2. Add a warning to README.
3. Any kind of additional flags or conditional disabling based on ghc version. If this is necessary at all depends on how quickly ghc is fixed. I probably would not bother as i cannot see a quick to implement solution that is better in all cases (e.g. for those that want -Wall vs those that want quick compiles.)

Did you have a look at my sublime+ghcid gist?

**Comment by ndmitchell** [comment]
The readme now includes:

* _I'm not seeing pattern matching warnings._ Ghcid automatically appends `-fno-code` to the command line, which makes the reload cycle about twice as fast. Unfortunately GHC 8.0 suffers from [bug 10600](https://ghc.haskell.org/trac/ghc/ticket/10600) which means `-fno-code` also disables pattern matching warnings. Until that GHC bug is fixed either accept no pattern match warnings or use `-c` to specify a command line to start `ghci` that doesn't include `-fno-code`.

Is that enough?

For the gist, I went through it briefly, but it does seem the wait a second and refresh approach is both too slow for some projects and way too short for others - I have some projects where a reload is typically ~5s. A custom sublime plugin seems like a necessary route. However, we should certainly document what we have now if we don't go that route - never harmful.

**Comment by lspitzner** [comment]
I'm fine with that README.

I agree with the refresh problems, after some more usage the rate of "bad updates" is higher than i like. But you can always remove any `sleep`ing and not use any build-on-save, and rely on pressing `ctrl-b`. One mostly does notice if the output is not updated yet. This way, you still get the jump-to-location functionality.

**Comment by ndmitchell** [comment]
I've raised #77 for the Sublime pieces and will consider the `-fno-code` thing closed by documenting it. If it ends up being a bigger problem than we thought we can revisit it.
