### ISSUE TITLE
is there a way to supply a second expression to --test?

### ISSUE THREAD

**Issue by mwotton** [ndmitchell/ghcid#79]
I want to stash a little bit of data at the end of my test run (it's in an env var, I just want to write its value to a file).

The use case for this: Hspec has --rerun, which is the reason I'm using ghcid in the first place. This is really useful for drilling in and staying on a particular set of failing tests until they pass. Quite often I need to change files in libraries that my main app depends on: unfortunately this requires a stack rebuild. currently i'm using a process like this:

```
stack build --dry-run --file-watch hestia 2>&1 | sed -u 's/ExitSuccess/\x0/g' | while read -d $'\0' x; do   
    echo "$x" | grep -q "missing dependencies"
    if [ $? -eq 0 ]; then echo "rebuilding"; touch ./rebuild; fi; done
rebuilding
```

and passing --restart rebuild to the ghcid invocation - unfortunately the HSPEC_FAILURES env var obviously doesn't survive the restart. If I could add a stanza to --test that could reload the env var from disk, and a trailing stanza that wrote the env var back to disk, i'd be done.

**Comment by ndmitchell** [comment]
Would making multiple `--test` arguments accumulate, and then running them one after another be sufficient?

**Comment by ndmitchell** [comment]
All `ghcid` actions are in the same process until you do something like edit the `.cabal` file, so that should be fine.

**Comment by mwotton** [comment]
(update: i found a way to jam it into hspec instead, but I still think this would be a useful feature.)

**Comment by ndmitchell** [comment]
I now support multiple test flags - it's basically the same as putting newlines between the test command.

**Comment by mwotton** [comment]
Fantastic, thanks.
