### ISSUE TITLE
Ctrl C sometimes stops working

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/ghcid#80]
Seems to be following the refactoring to make the tests work better.

**Comment by ndmitchell** [comment]
It seems like it does work now. I'll have to see if I can reproduce.

**Comment by timhabermaas** [comment]
Seems to now work reliably with 0.6.5. Thanks!

**Comment by ndmitchell** [comment]
With HEAD pressing Ctrl-C does close the child process if it works, but sometimes stops working. I've added diagnostics code for my testing, and will see what I can see - there are definitely still bugs here (but it's certainly possible they are Windows only).

**Comment by ndmitchell** [comment]
It now seems a lot more reliable, I did another audit and fixed #154 which may have been part of the issue.
