### ISSUE TITLE
ctrl-c does not kill child process

### ISSUE THREAD

**Issue by lspitzner** [ndmitchell/ghcid#81]
i just managed to enter heavy-swapping-mode after repeatedly killing ghcid and restarting it while switching branches (with modifications to my .cabal). Noticed several 100% cpu (one core) `ghc --interactive` processes hogging significant amounts of memory each.

**Comment by ndmitchell** [comment]
In the changes I've been making since the last release I included making sure ctrl-c cleans up the `ghci` processes properly. Alas, in doing so I introduced #80 - the opposite problem. But I'll try and tackle both simultaneously so as to make sure this one gets fixed at the same time.

**Comment by ndmitchell** [comment]
I believe version 0.6.5 fixes this, let me know if not.

**Comment by timhabermaas** [comment]
@ndmitchell 0.6.5 fixes this problem for me (Mac OS X 10.11.6, iTerm 2). Thanks a lot!

**Comment by ndmitchell** [comment]
Needs tackling in conjunction with #80, so closing this and focusing the effort there.
