### ISSUE TITLE
Strange CallStack error

### ISSUE THREAD

**Issue by afcowie** [ndmitchell/ghcid#84]
Every time I run **ghcid** in a project using GHC 8 via stackage snapshot `nightly-2016-08-06`, I get:

```
CallStack (from HasCallStack):
  error, called at <interactive>:8:1 in interactive:Ghci3
```
before my program's output. My original incantation was more elaborate, but I boiled it down to:

```shell
$ ghcid --test=:main
```

**Comment by ndmitchell** [comment]
Can you try using HEAD? I've fixed a few GHC 8 call stack issues in that.

**Comment by afcowie** [comment]
That seems to have done it. Thanks!

**Comment by ndmitchell** [comment]
Great - I'll aim to make a release in the next few days.
