### ISSUE TITLE
Language.Haskell.Ghcid.startGhci never returns with intero

### ISSUE THREAD

**Issue by rvion** [ndmitchell/ghcid#85]
I'm using Language.Haskell.Ghcid as a library

🔴 when I try to start it with `stack ghci --with-ghc intero` command, it never returns. 

🍏 when I try to start it with `stack ghci` command, it returns. 

------------

log when I start my app with `stack ghci --with-ghc intero` :

```
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Using main module: 1. Package `ws-proxy' component exe:ws-proxy with main-is file: /Users/rvion/dev/slime-wars/ws-proxy/src/Main.hs
Configuring GHCi with the following packages: ws-proxy
Intero 0.1.18 (GHC 8.0.1)
Type :intro and press enter for an introduction of the standard commands.

[1 of 2] Compiling WS               ( /Users/rvion/dev/slime-wars/ws-proxy/src/WS.hs, interpreted )
[2 of 2] Compiling Web              ( /Users/rvion/dev/slime-wars/ws-proxy/src/Web.hs, interpreted )
Ok, modules loaded: Web, WS.
Collecting type info for 2 module(s) ...
[3 of 3] Compiling Main             ( /Users/rvion/dev/slime-wars/ws-proxy/src/Main.hs, interpreted )

/Users/rvion/dev/slime-wars/ws-proxy/src/Main.hs:34:3: warning: [-Wunused-matches]
    Defined but not used: ‘mbghci’

/Users/rvion/dev/slime-wars/ws-proxy/src/Main.hs:36:8: warning: [-Wunused-matches]
    Defined but not used: ‘ghci’
Ok, modules loaded: Web, WS, Main.
Collecting type info for 3 module(s) ...

/Users/rvion/dev/slime-wars/ws-proxy/src/Main.hs:34:3: warning: [-Wunused-matches]
    Defined but not used: ‘mbghci’

/Users/rvion/dev/slime-wars/ws-proxy/src/Main.hs:36:8: warning: [-Wunused-matches]
    Defined but not used: ‘ghci’
^C
```

log when I start my app with `stack ghci`:

```
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Using main module: 1. Package `ws-proxy' component exe:ws-proxy with main-is file: /Users/rvion/dev/slime-wars/ws-proxy/src/Main.hs
Configuring GHCi with the following packages: ws-proxy
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
[1 of 2] Compiling WS               ( /Users/rvion/dev/slime-wars/ws-proxy/src/WS.hs, interpreted )
[2 of 2] Compiling Web              ( /Users/rvion/dev/slime-wars/ws-proxy/src/Web.hs, interpreted )
Ok, modules loaded: Web, WS.
[3 of 3] Compiling Main             ( /Users/rvion/dev/slime-wars/ws-proxy/src/Main.hs, interpreted )

/Users/rvion/dev/slime-wars/ws-proxy/src/Main.hs:34:3: warning: [-Wunused-matches]
    Defined but not used: ‘mbghci’

/Users/rvion/dev/slime-wars/ws-proxy/src/Main.hs:36:8: warning: [-Wunused-matches]
    Defined but not used: ‘ghci’
Ok, modules loaded: Web, WS, Main.
Loaded GHCi configuration from /private/var/folders/gc/wcfbw22111q17bwh607qqlg00000gn/T/ghci51540/ghci-script
ok
```

**Comment by rvion** [comment]
Some Context:

 - I'm building a small web ide
 - ghcid is great, but I want to have autocompletion, type information, etc.
 - I wrote my own ghcid-like wrapper around ghci, but it's much much less robust than ghcid library, so I wanted to switch over ghcid library to handle communication with intero
 - I know about https://github.com/JPMoresmau/reload but it lacks a few features I really want (eg: quickly showing the type of the smallest ast node enclosing my selection)
 - I know about https://github.com/myfreeweb/intero/commits/master intero fork with messagepack rpc server but I'm not quite confident in starting from there

@JPMoresmau I really understand you when you say the current state of tooling is saddening ^^
Everything seems to be so close, yet it never "just works" :/ ghc-mod is too slow for large projetcs (> 10 times slower  than intero in medium/large projects for ~ the same features), ghci codebase is not pleasant to work with, intero didn't refactor ghci to add a proper ide-server architecture (no proper RPC, too many features are done emacs-side in elisp instead of haskell, etc.), hdevtools, hsdev, etc, are either slow or too basic...  I don't really like the way haskell-ide-engine architecture went. When I add on top of that the fact that I don't really like emacs and vim (I can cope with them, but I prefer modern editors like atom or ST with decent multi-cursors ability, "sane" default configuration, etc.)

😢 The sad thing is that I think that a more concerted effort would have solve the problem once for all in a few days ! I have the impression that it's just about merging (ghci + intero + ghcid)  refactor the codebase and adding better way to interact with it as an ide-server.

**Comment by ndmitchell** [comment]
It seems like when you start using `stack ghci --with-ghc intero` you never get to the interactive prompt? That's what `ghcid` is looking for, whether through a library or the tool. It changes the prompt, then sends messages to the prompt and only continues once it has seen them echoed.

**Comment by ndmitchell** [comment]
(And yeah, the Haskell IDE story sucks - good luck with whatever you are trying in this area!)

**Comment by ndmitchell** [comment]
Seems like there's no fault with ghcid here, so I'll leave it to be raised with intero. Let me know if you think there is something more ghcid could be doing.
