### ISSUE TITLE
Prevent ghci from stripping ANSI colour from output?

### ISSUE THREAD

**Issue by afcowie** [ndmitchell/ghcid#87]
Is there a way to make coloured output of commands invoked via `--test` not be stripped of their colourization?

I've got **ghcid** running an **hspec** test for me, and on console it's coloured but in ghcid it's not. This, of course, is the harbinger of the end of the universe, and clearly needs urgent fixing.

(I'm guessing it's probably Test.HSpec thinking it's not a terminal and so is suppressing ANSI escape codes, but perhaps there's something that **ghcid** could do to sway it otherwise? Although it's speaking to ghci over stdin/stdout [?] it most assuredly is a console program with a human in front of it)

AfC

**Comment by ndmitchell** [comment]
Is there a command line flag to `hspec` to say use colour all the time, rather than just when you detect a terminal? I'm not sure how hspec is guessing at whether I'm a terminal, and thus I don't know how to influence that... I imagine it uses `hIsTerminalDevice` at some point, and I don't think there's any way to fake that - I'm not really a a terminal device, I just happen to know I'm going to put the results back onto a terminal with minimal munging.

**Comment by Wizek** [comment]
I've been working around this issue like this for a while now:

```hs
import qualified  Test.Hspec.Runner                     as Hspec

mainColor = Hspec.hspecWith
  Hspec.defaultConfig{Hspec.configColorMode=Hspec.ColorAlways} spec
```

Not perfect, but usually works quite well. Sharing in case others, e.g. @afcowie find it useful.

If anyone has an even better solution or just a better workaround, I'm all ears.

E.g. AFAIK Hspec has a CLI flag to force colors. IIRC `--color`. Maybe it would also work to set args in ghci via something like `:args ["--color"]` before invoking hspec's main. Anyone experimented with this or something else?

**Comment by ndmitchell** [comment]
If you do `-T ":main --color"` does that work? As far as I can tell there are two pieces to the problem:

* Getting HSpec to put out colors. You should be able to do this with a flag. Is there another way to specify that you want colors? Anything I can drive automatically from ghcid?
* Getting those colors into ghcid. If they come out as escape codes, then ghcid probably (?) gets the line wrapping wrong by miscalculating the number of characters. On Windows, going via Win32 API console codes, they might just get entirely lost - not sure what hspec does here.

While some people might consider it a liveable problem, other people such as @intolerable consider it basically fatal...

**Comment by Wizek** [comment]
Yes, `-T ":main --color"` does work!
And so does `-T ':set args ["--color"]' -T main`.

> If they come out as escape codes

I don't think this is a problem on linux. At least I haven't encountered it in the many sessions I had colors enabled.

> Anything I can drive automatically from ghcid?

That would be nice, but I am not quite sure how.

One thing that comes to mind: We maybe can somehow convince the driven ghci process that it is indeed in a tty, after all.
A way to achieve this: http://stackoverflow.com/questions/1401002/trick-an-application-into-thinking-its-stdin-is-interactive-not-a-pipe

Related hspec issue: https://github.com/hspec/hspec/issues/158

@sol, as the author of hspec, what do you think about the above discussion? Might you have any ideas how it could make sense for ghcid and hspec to interact in a way that shows color for end users without hassle, automatically?

**Comment by Wizek** [comment]
Browsing further, I've found another, perhaps even more related hspec issue: https://github.com/hspec/hspec/issues/34

Which lead me to this code section: https://github.com/hspec/hspec/blob/307b906612ce3344a7e8a1a0e127ad9cfaa5b7e9/hspec-core/src/Test/Hspec/Core/Runner.hs#L203

( Source for hIsTerminalDevice: https://hackage.haskell.org/package/base-4.9.1.0/docs/src/GHC.IO.Handle.html#hIsTerminalDevice )

**Comment by sol** [comment]
@Wizek @afcowie recent versions of `hspec` read command-line options from the config files `.hspec` and `~/.hspec`.  You can tell `hspec` to always colorize output with:

```
$ echo --color >> ~/.hspec
```

We can consider to also read command-line options from an environment variable, e.g. `HSPEC_OPTIONS`.  This would allow `ghcid` to pass `--color` to `hspec` by setting / modifying that environment variable.

@ndmitchell I can't comment on Windows.  Regarding counting characters for output that contains ANSI color sequences, I think it's plausible that this won't yield the expected result.

**Comment by ndmitchell** [comment]
I'm happy to always set the env variable in ghcid. I suspect it wouldn't work on Windows unless you were in a bash shell, but I can fix that on the ghcid side so can sort it out then.

**Comment by Wizek** [comment]
@sol Glad to hear we have the `~/.hspec` option and might have the env variable option too! This is definitely mitigating the issue even further.

And `HSPEC_OPTIONS` sounds specific enough that, as @ndmitchell is commenting, setting it always from ghcid could -- without interfering with anything else -- yield the expected result for new users automatically wrt. ghcid + hspec + colors.

I do still wonder if there is some solution that could be even more generic, that doesn't assume hspec at the other end. E.g. [faketty](http://stackoverflow.com/a/20401674/499478) or similar might be able to give us ghcid + X + colors.

But I am willing to let that go for now as the proposed `HSPEC_OPTIONS` env variable does indeed solve this specific issue quite thoroughly.

***

I am not sure if you are aware, as an aside, that while cmd.exe on Windows does indeed not support ANSI color control characters, PowerShell does.

**Comment by sol** [comment]
As a side note, if you use `hspec` with `ghcid` you may find `--rerun` and `--rerun-all-on-success` useful.

**Comment by sol** [comment]
`hspec-2.4.3` adds support for `HSPEC_OPTIONS`

**Comment by afcowie** [comment]
@ndmitchell can we have **ghcid** emit the `HSPEC_OPTIONS` environment variable now?

**Comment by ndmitchell** [comment]
@afcowie Sure, but you should be able to do it on your side pretty easily - or is this some magic that _only_ ghcid can accomplish? It's the Windows issue that makes it harder.

**Comment by afcowie** [comment]
@ndmitchell you're right, of course. Just seems somewhat awesome to have to set `HSPEC_OPTIONS` in _~/.ḃashrc_ to be inherited by all processes when only the communication between **ghcid** and a child program (which isn't even a child, it's in the same process space, hm) linking against **hspec** needs to be influenced. To be honest it seems as this is in the category of "it should just work, transparently" and so if you're willing to add it, wonderful; if not, so be it.

AfC

**Comment by ndmitchell** [comment]
Should probably also pass `-fdiagnostics-color=always` once I can, so that the GHC error messages come out coloured too.

**Comment by ndmitchell** [comment]
@afcowie I'm keen to get it working with ANSI escape codes, then I'll be happy to enable it unconditionally for both HSPEC and GHC.

**Comment by ndmitchell** [comment]
Done. For Windows, HSpec sends codes directly to the console, rather than escape codes, so the act of redirecting stdout by construction removes the colors. It's a shame, as Windows 10 supports escape codes, which is what GHC uses, and thus the information can be preserved. For Linux/Mac users, it should just work.
