### ISSUE TITLE
(nvim plugin) Please mention in the readme how it interacts with neomake

### ISSUE THREAD

**Issue by expipiplus1** [ndmitchell/ghcid#91]
I use neomake for hlint checks too (thanks Neil!). It would be nice to have mentioned in the readme how this interacts with neomake in terms of sharing the quickfix window.

**Comment by cloudhead** [comment]
I'm assuming they don't work well together? Or could you tell me what you wish you had known?

**Comment by expipiplus1** [comment]
I have to admit I've not used them together, it would be nice to have some assurance that they'll work well together or step on each other's toes.

I'll leave this on my todo list and report back here when I've tried it out.

**Comment by cloudhead** [comment]
Ah I see. I haven't tried to use them together, but I don't think there should be a big problem. I'm guessing whichever runs last will take over the quickfix list and signs column.

**Comment by cloudhead** [comment]
Closing, feel free to re-open if you discover something unexpected.
