### ISSUE TITLE
hs-boot exception

### ISSUE THREAD

**Issue by lspitzner** [ndmitchell/ghcid#94]
I see an error with hs-boot again unfortunately, but it seems on ghci's end. if the .hs file (where a corresponding hs-boot, without errors, exists) contains error(s), i see the following output from ghci:

> Failed, modules loaded: Language.Haskell.Brittany.Backend (dist/build/Language/Haskell/Brittany/Backend.o), Language.Haskell.Brittany.BackendUtils (dist/build/Language/Haskell/Brittany/BackendUtils.o), Language.Haskell.Brittany.Config (dist/build/Language/Haskell/Brittany/Config.o), Language.Haskell.Brittany.Config.Types (dist/build/Language/Haskell/Brittany/Config/Types.o), Language.Haskell.Brittany.ExactPrintUtils (dist/build/Language/Haskell/Brittany/ExactPrintUtils.o), Language.Haskell.Brittany.LayouterBasics (dist/build/Language/Haskell/Brittany/LayouterBasics.o), Language.Haskell.Brittany.Layouters.Decl (dist/build/Language/Haskell/Brittany/Layouters/Decl.o), *** Exception: expectJust showModule
> CallStack (from HasCallStack):
>  error, called at compiler/utils/Maybes.hs:48:27 in ghc:Maybes

And consequently reloading does not work, because modules (especially `INTERNAL_GHCID`) are not reloaded, which then makes ghcid hang. This all happens deterministically.

ghc-8.0.2

Now this seems mostly like a ghc bug, so my question: have you seen this/reported it already; and can you think of a workaround?

**Comment by ndmitchell** [comment]
I haven't seen it, and it does seem like a pretty bad GHCi bug. I suggest you report it upstream at the GHC trac (and post the link here) - they may have a workaround. Note that GHCi seems pretty buggy in general, and I often find regressions between versions - although usually not as obvious and clear cut as above.

**Comment by lspitzner** [comment]
https://ghc.haskell.org/trac/ghc/ticket/13591#ticket

**Comment by lspitzner** [comment]
The fix i wrote has made it into GHC-8.2.1, and i can confirm that `ghcid` now works as desired for hs-boot.
