### ISSUE TITLE
When enabling ghci coloured error message, everything is always "All good"

### ISSUE THREAD

**Issue by edsko** [ndmitchell/ghcid#96]
Colours apparently make ghcid so happy that no matter whether there is are errors/warnings or not, it always just shows "All good" :) Of course, I have to go out of my way to _get_ these colours in the first place

```
ghcid --command='cabal new-repl --ghc-option=-fdiagnostics-color=always' 
```

so it's easy to workaround but the colours are helpful, would be nice to keep them.

**Comment by ndmitchell** [comment]
It doesn't work with my GHC 8.0.1, so is this a GHC 8.2 only feature? Or a Linux only feature? `ghcid` already rewrites all the output, and I guess it does so in a way that doesn't preserve color? So I guess it needs to preserve it, parse through it, and redisplay it. All imminently doable, if I can reproduce. I also worry whatever I do will be different on Windows, and thus I won't be able to benefit from colored output (Idris has spoilt me).

**Comment by edsko** [comment]
Ah, yes, sorry, I should have mentioned that. This is a new feature in 8.2.

**Comment by ndmitchell** [comment]
Interestingly on Windows, colours are making my code very sad. Things I notice fairly quickly:

* If there is an error and you have forced colors then the filename gets mangled. If that happens it keeps reloading. Two part fix - don't screw up the filename, don't infinite reload if filenames are screwed up.
* Sometimes you get | on a single line, which isn't a lot of information. Should strip that if it occurs.
* Should probably parse the escape codes, and put them back in later, so they work even on Windows.

**Comment by ndmitchell** [comment]
I now disable the coloured diagnostics if at all possible, which fixes the problems. As part of #87 I'll work to keep them.
