### ISSUE TITLE
Starting nvim plugin when there are errors doesn't work

### ISSUE THREAD

**Issue by cloudhead** [ndmitchell/ghcid#97]
If the source code contains errors when `:Ghcid` is called for the first time, it sometimes stops loading before the errors are shown.

**Comment by adelbertc** [comment]
I am observing this as well I think.

When I start `:Ghcid` I see a bunch of output, it hits the first warning, and then no more output follows after that. Making changes to a file does not seem to be able to cause ghcid to reload, and running `:Ghcid` again which presumably toggles the window open/closed causes it to crash/die.

**Comment by cloudhead** [comment]
You're saying you have this problem with vanilla ghcid? If so, perhaps this isn't a problem with the plugin.

**Comment by cloudhead** [comment]
Can't reproduce this anymore. Closing until it comes back up.
