### ISSUE TITLE
Provide a "server" mode

### ISSUE THREAD

**Issue by 3noch** [ndmitchell/ghcid#99]
When working with servers it's common that you want to restart the server on file change. This *almost* works as is by using `--test`. However, since the server never terminates, it doesn't actually work. I tried to think of a way around this by creating a tricky `forkIO/killThread` version of server. However I haven't found a good way to achieve this.

**Comment by jmn** [comment]
Having this functionality would make ghcid more useful for web/server development.
[Ordeal ](https://github.com/reiddraper/ordeal) can do automatic server restarting in GHCi. Not for Windows unfortunately - AFAICT - as it relies on the unix/System.Posix package.

**Comment by 3noch** [comment]
Oh, you're right! According to that blog post, `test` should interrupt the running code. I thought I had tried that but I'll double-check.

**Comment by ndmitchell** [comment]
@3noch - does this work? It should, as long as your code properly deals with async exceptions and doesn't just eat them.

**Comment by 3noch** [comment]
@ndmitchell Yes! Sorry I should have closed this. This does work.
